### ISSUE TITLE
[kernels] move from initramfs/vmlinuz-3xx to initramfs/vmlinuz-3.xx

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#10]
Currently we have followed initramfs/vmlinuz structure:
<pre>initramfs-310-x86_64-fallback.img
initramfs-310-x86_64.img
initramfs-312-x86_64-fallback.img
initramfs-312-x86_64.img
initramfs-313-x86_64-fallback.img
initramfs-313-x86_64.img
initramfs-314-x86_64-fallback.img
initramfs-314-x86_64.img
initramfs-316-x86_64-fallback.img
initramfs-316-x86_64.img
initramfs-318-x86_64-fallback.img
initramfs-318-x86_64.img
initramfs-319-x86_64-fallback.img
initramfs-319-x86_64.img
initramfs-40-x86_64-fallback.img
initramfs-40-x86_64.img
intel-ucode.img
linux310-x86_64.kver
linux312-x86_64.kver
linux313-x86_64.kver
linux314-x86_64.kver
linux316-x86_64.kver
linux318-x86_64.kver
linux319-x86_64.kver
linux40-x86_64.kver
vmlinuz-310-x86_64
vmlinuz-312-x86_64
vmlinuz-313-x86_64
vmlinuz-314-x86_64
vmlinuz-316-x86_64
vmlinuz-318-x86_64
vmlinuz-319-x86_64
vmlinuz-40-x86_64
</pre>

Since 40 is lower than for example 310, kernel 4.0 get noticed as oldest kernel installed. Therefor it will be listed last in grub.cfg on multible kernel installations. Moving to followed structure will fix this:

<pre>initramfs-3.10-x86_64-fallback.img
initramfs-3.10-x86_64.img
initramfs-3.12-x86_64-fallback.img
initramfs-3.12-x86_64.img
initramfs-3.13-x86_64-fallback.img
initramfs-3.13-x86_64.img
initramfs-3.14-x86_64-fallback.img
initramfs-3.14-x86_64.img
initramfs-3.16-x86_64-fallback.img
initramfs-3.16-x86_64.img
initramfs-3.18-x86_64-fallback.img
initramfs-3.18-x86_64.img
initramfs-3.19-x86_64-fallback.img
initramfs-3.19-x86_64.img
initramfs-4.0-x86_64-fallback.img
initramfs-4.0-x86_64.img
intel-ucode.img
linux310-x86_64.kver
linux312-x86_64.kver
linux313-x86_64.kver
linux314-x86_64.kver
linux316-x86_64.kver
linux318-x86_64.kver
linux319-x86_64.kver
linux40-x86_64.kver
vmlinuz-3.10-x86_64
vmlinuz-3.12-x86_64
vmlinuz-3.13-x86_64
vmlinuz-3.14-x86_64
vmlinuz-3.16-x86_64
vmlinuz-3.18-x86_64
vmlinuz-3.19-x86_64
vmlinuz-4.0-x86_64
</pre>

**Comment by philmmanjaro** [comment]
We have to check at least followed packages:
* calamares
* grub
* manjaro-tools
* thus

**Comment by Kirek** [comment]
thus, and calamares doesn't need to be changed, its manjaro-tools' job to provide the right strings.

**Comment by philmmanjaro** [comment]
@Kirek: I think I thought we had some vmlinuz copy cmd hardcoded. So I've to check that.

**Comment by philmmanjaro** [comment]
Done for 310, 314 and 319 within f6ef6bfaf90b0edb825cdd8b9d726c3a54207379 and c75a08574217d8f17b8ab1f53c7426f328f25ff2

**Comment by philmmanjaro** [comment]
**syslinux** users may need to edit their configs manually.

Example
----------------

From:
<pre>initramfs-319-x86_64-fallback.img
initramfs-319-x86_64.img
vmlinuz-319-x86_64</pre>

To:
<pre>initramfs-3.19-x86_64-fallback.img
initramfs-3.19-x86_64.img
vmlinuz-3.19-x86_64</pre>

----

Grub will manage this change automatically.

**Comment by philmmanjaro** [comment]
linux316 might be updated this [Saturday](http://www.spinics.net/lists/kernel/msg1972574.html) ...

**Comment by philmmanjaro** [comment]
Done for 318 within 52a8a53137f660ef184ede7b32b199104006b572

**Comment by philmmanjaro** [comment]
Done for 316 within 1dbf4292a5498b54db9c9c2ac54685e4c2ceba5b

**Comment by philmmanjaro** [comment]
Done for 40, 312 and 313 within 95c941a8ec2879cc34e1c5ae16b2d9ad7f95eca5, be9dea08cda99ff49886481345fbaaa9e889ab95, baee55832fbf1cca8fb8e952baccd4ebd40844bf
