### ISSUE TITLE
gcc with antispectre

### ISSUE THREAD

**Issue by bn0785ac** [manjaro/packages-core#104]
when will gcc with antispectre arrive to manjaro?  https://www.archlinux.org/packages/core/x86_64/gcc/

https://www.phoronix.com/scan.php?page=news_item&px=GCC-7.3-Thursday

**Comment by bn0785ac** [comment]
other question (related)


will manjaro rebuild ALL PACKAGES with gcc (antispectre)

or just the kernel

**Comment by jonathonf** [comment]
Please check the forum for discussion on package updates.
