### ISSUE TITLE
error during pacman-mirrors update

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-core#106]
@fhdk during update with latest **pacman-mirrors** pkg I get this error when hooks are executed.
```
(4/8) Configuring pacman-mirrors ...
.: ERROR: Invalid setting in `/etc/pacman-mirrors.conf`
     SSLVerfy = True. EXPECTED ('True', 'False')
```
I'm not aware that I have ever edited the file manually - maybe I have?

**Comment by oberon2007** [comment]
It's apparently an issue in the package itself because after removing the file and reinstalling the package, the error is there appearing.

**Comment by oberon2007** [comment]
Maybe just missing quotes?

**Comment by Ste74** [comment]
Also here
https://forum.manjaro.org/t/pacman-mirrors-4-7-2-config-file-sanity-check/40171/2

**Comment by oberon2007** [comment]
Exactly! The i is missing in Verify! ;)
Not in the config file, but the default in the source must be misspelled ;)

**Comment by oberon2007** [comment]
Ok. I see @fhdk has already fixed it in the source! :)

**Comment by oberon2007** [comment]
https://github.com/manjaro/pacman-mirrors/commit/dbd6cd42ac2c609fe8d88bd15121e4e561cd86e2

**Comment by oberon2007** [comment]
Well but now there's a new error! ;) @fhdk 
```
(1/2) Configuring pacman-mirrors ...
Traceback (most recent call last):
  File "/usr/bin/pacman-mirrors", line 57, in <module>
    pm.run()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 874, in run
    (self.config, self.custom) = configFn.build_config()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/functions/configFn.py", line 83, in build_config
    if not verify_config(config):
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/functions/configFn.py", line 105, in verify_config
    ", ".join(config["ssl_verify"]), txt.EXP_CLR, conf.SSL))
TypeError: can only join an iterable

```

**Comment by oberon2007** [comment]
@fhdk please test installilng the package locally before pushing, especially before pushing to stable branch!
Thanks 😄

**Comment by oberon2007** [comment]
**4.7.2-2** is still faulty, see above.

**Comment by oberon2007** [comment]
Here's pkgrel 3:
```
(1/2) Configuring pacman-mirrors ...
.: ERROR: Invalid setting in `/etc/pacman-mirrors.conf`
     'SSLVerify = True'; EXPECTED True|False
```
@fhdk

**Comment by oberon2007** [comment]
pkgrel 4 seems to be working.

**Comment by fhdk** [comment]
I am sorry - I really am.

The issue was a total oversight by me.

I compared a bool True/False with the string True/False - which made pacman-mirrors die immediately.

When I changed it to `if str(config["ssl_verify"]) not in conf.SSL` which fixed the issue.

I don't know how I could miss it - so - sorry for the inconvenience.

**Comment by oberon2007** [comment]
It's fine now. Just would be good to check locally or at least on unstable first before forwarding to all branches ... 😜

**Comment by fhdk** [comment]
You are absolutely right - I kind of paniced - when I realized I had made a major .....
