### ISSUE TITLE
Data corruption on software RAID 0 when discard is used

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#11]
Recent Linux kernels, pushed to the stable branch within the last [update](https://manjaro.github.io/Update-2015-05-17_(stable)/), suffered from a bug that can cause data corruption on file systems mounted with the discard option and residing on software RAID 0 arrays. Even if discard is not specified, the fstrim command can also trigger this bug. (If you do not use software RAID 0 or the discard option, then this issue does not affect you.)

Due to the nature of the bug, however, it is likely that data corruption has already occurred on systems running the aforementioned kernels. It is strongly advised to verify the integrity of affected file systems using fsck and/or restore their data from known good backups.

We will soon notify you, when we fixed this issue.

**Comment by philmmanjaro** [comment]
**linux310** and **linux312** are **NOT** affected due this.

**Comment by philmmanjaro** [comment]
**linux314**, **linux318** and **linux40** are currently fixed in our [unstable branch](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150525/003307.html).

**Comment by philmmanjaro** [comment]
**linux313** is NOT affected due this.

**Comment by philmmanjaro** [comment]
Still open to fix are **linux316** and **linux319** ...

**Comment by philmmanjaro** [comment]
**linux316** and **linux319** fixed in our [unstable branch](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150525/003314.html)

**Comment by philmmanjaro** [comment]
The issue was caused by an MD commit late into the Linux 4.0 kernel cycle, a.k.a. commit 47d68979cc968535cb87f3e5f2e6a3533ea48fbd that was md/raid0: fix bug with chunksize not a power of 2.. The commit by SUSE's Neil Brown explained, "Since commit 20d0189b1012a37d2533a87fb451f7852f2418d1 in v3.14-rc1 RAID0 has performed incorrect calculations when the chunksize is not a power of 2. This happens because sector_div() modifies its first argument, but this wasn't taken into account in the patch. So restore that first arg before re-using the variable."

The variable "sector" in "raid0_make_request()" was improperly updated by a call to "sector_div()" which modifies its first argument in place. Commit 47d68979cc968535cb87f3e5f2e6a3533ea48fbd restored this variable after the call for later re-use.  Unfortunetly the restore was done after the referenced variable "bio" was advanced.  This lead to the original value and the restored value being different.  Here we move this line to the proper place.

One observed side effect of this bug was discarding a file though unlinking would cause an unrelated file's contents to be discarded.

**Comment by Barthalion** [comment]
Wow, it looks like I have read it [somewhere](https://www.archlinux.org/news/data-corruption-on-software-raid-0-when-discard-is-used/) [already](http://git.neil.brown.name/?p=md.git;a=commitdiff;h=a81157768a00e8cf8a7b43b5ea5cac931262374f).

**Comment by philmmanjaro** [comment]
All kernels in our [testing branch](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150525/003321.html) are now also fixed.

**Comment by philmmanjaro** [comment]
All kernels are now in stable branch too.
