### ISSUE TITLE
[linux] older LTS kernels are not compatible to gcc 5.1

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#12]
As of now kernels lower than **linux318** are not compatible to gcc 5.1.

Affected kernels:
* linux310
* linux312
* linux313 (not yet tested)
* linux314
* linux316

Common issues:
<pre>lib/mpi/generic_mpih-mul1.o: In function `mpihelp_add_1':
generic_mpih-mul1.c:(.text+0x0): multiple definition of `mpihelp_add_1'
lib/mpi/generic_mpih-lshift.o:generic_mpih-lshift.c:(.text+0x0): first defined here
lib/mpi/generic_mpih-mul1.o: In function `mpihelp_add':
generic_mpih-mul1.c:(.text+0x70): multiple definition of `mpihelp_add'
lib/mpi/generic_mpih-lshift.o:generic_mpih-lshift.c:(.text+0x70): first defined here
lib/mpi/generic_mpih-mul1.o: In function `mpihelp_sub_1':
generic_mpih-mul1.c:(.text+0x130): multiple definition of `mpihelp_sub_1'
lib/mpi/generic_mpih-lshift.o:generic_mpih-lshift.c:(.text+0x130): first defined here
lib/mpi/generic_mpih-mul1.o: In function `mpihelp_sub':
generic_mpih-mul1.c:(.text+0x1a0): multiple definition of `mpihelp_sub'
lib/mpi/generic_mpih-lshift.o:generic_mpih-lshift.c:(.text+0x1a0): first defined here</pre>

<pre>drivers/scsi/qla2xxx/qla_nx2.c:1541:1: error: static declaration of 'qla8044_need_reset_handler' follows non-static declaration
 qla8044_need_reset_handler(struct scsi_qla_host *vha)
 ^
In file included from drivers/scsi/qla2xxx/qla_def.h:3542:0,
                 from drivers/scsi/qla2xxx/qla_nx2.c:10:
drivers/scsi/qla2xxx/qla_gbl.h:732:20: note: previous declaration of 'qla8044_need_reset_handler' was here
 extern inline void qla8044_need_reset_handler(struct scsi_qla_host *vha);
                    ^
drivers/scsi/qla2xxx/qla_gbl.h:732:20: warning: inline function 'qla8044_need_reset_handler' declared but never defined
scripts/Makefile.build:308: recipe for target 'drivers/scsi/qla2xxx/qla_nx2.o' failed</pre>

<pre>drivers/staging/rtl8187se/r8180_wx.o: In function `ieee80211_increment_scans':
r8180_wx.c:(.text+0x1720): multiple definition of `ieee80211_increment_scans'
drivers/staging/rtl8187se/r8180_core.o:r8180_core.c:(.text+0x38c0): first defined here
drivers/staging/rtl8187se/r8180_wx.o: In function `ieee80211_get_scans':
r8180_wx.c:(.text+0x1730): multiple definition of `ieee80211_get_scans'
drivers/staging/rtl8187se/r8180_core.o:r8180_core.c:(.text+0x38d0): first defined here
drivers/staging/rtl8187se/r8180_rtl8225z2.o: In function `ieee80211_increment_scans':
r8180_rtl8225z2.c:(.text+0x570): multiple definition of `ieee80211_increment_scans'
drivers/staging/rtl8187se/r8180_core.o:r8180_core.c:(.text+0x38c0): first defined here</pre>

<pre>drivers/staging/rtl8192e/rtl8192e/r8192E_phy.o: In function `rtllib_increment_scans':
r8192E_phy.c:(.text+0x3f0): multiple definition of `rtllib_increment_scans'
drivers/staging/rtl8192e/rtl8192e/r8192E_dev.o:r8192E_dev.c:(.text+0xd0): first defined here
drivers/staging/rtl8192e/rtl8192e/r8192E_phy.o: In function `rtllib_get_scans':
r8192E_phy.c:(.text+0x400): multiple definition of `rtllib_get_scans'
drivers/staging/rtl8192e/rtl8192e/r8192E_dev.o:r8192E_dev.c:(.text+0xe0): first defined here</pre>

**Comment by Kirek** [comment]
At least linux314 works for arch with this patch https://projects.archlinux.org/svntogit/packages.git/tree/trunk/gcc5_buildfixes.diff?h=packages/linux-lts

**Comment by philmmanjaro** [comment]
Some fixes can be found [here](https://grsecurity.net/changelog-stable2.txt). We have to create a clean backport for upstream:

<pre>commit 0366b7254987510c15531a1427dd36579e0377f4
Author: Brad Spengler <spender@grsecurity.net>
Date:   Mon Apr 27 07:31:18 2015 -0400

    Backport GCC 5.1 support

 include/linux/compiler-gcc5.h     |    3 --
 tools/gcc/colorize_plugin.c       |    4 +-
 tools/gcc/constify_plugin.c       |   11 +++++--
 tools/gcc/gcc-common.h            |   24 ++++++++++++++-
 tools/gcc/kallocstat_plugin.c     |   11 +++++--
 tools/gcc/kernexec_plugin.c       |   59 ++++++++++++++++++++++++++----------
 tools/gcc/latent_entropy_plugin.c |   12 +++++--
 tools/gcc/stackleak_plugin.c      |   22 ++++++++++---
 tools/gcc/structleak_plugin.c     |   25 ++++++++++++----
 9 files changed, 127 insertions(+), 44 deletions(-)</pre>

@Kirek: not all. Arch does a lazy job there. They simply patch some they found, but don't fix them all. Their solution is to disable some modules. Grsecurity did a proper backport. I'll ask Brad to send me a clean backport without those grsecurity patches in addition. Currently I'm building those kernels in stable branch with gcc 4.9.2.

**Comment by philmmanjaro** [comment]
As Greg Kroah-Hartman said:

> If you look, I've already added gcc 5.1 support to 3.14 and 3.10, this
> past weekend, the patches for this is in the stable queue and will show
> up in the next release in a few days or so.
> 
> greg k-h

You can find them [here](http://git.kernel.org/cgit/linux/kernel/git/stable/stable-queue.git/commit/?id=471766ee2f98c37623c7b5037cc759cf3b743259) and [here](http://git.kernel.org/cgit/linux/kernel/git/stable/stable-queue.git/commit/?id=471766ee2f98c37623c7b5037cc759cf3b743259).

**Comment by philmmanjaro** [comment]
**linux316** is fixed with followed patches:

As Luis Henriques said:

> Ok, so here's the list of commits I'm queuing:
> 
> 6d91857d4826 ("staging, rtl8192e, LLVMLinux: Change extern inline to static inline")
> 51b97e354ba9 ("kernel: use the gnu89 standard explicitly")
> 62ec95f86d28 ("staging, rtl8192e, LLVMLinux: Remove unused inline prototype")
> 0c9f3a65c5eb ("staging: rtl8712, rtl8712: avoid lots of build warnings")
> 9493c2422cae ("qla2xxx: remove redundant declaration in 'qla_gbl.h'")
> 
> I'm also queuing a non-upstream patch that has been included by Greg
> and Jiri in their stable trees:
> 
>   "staging: wlags49_h2: fix extern inline functions"
> 
> Finally, I had already queued the following:
> c097877319ab ("ARM: 8307/1: psci: move psci firmware calls out of line")
> 
> Do you see any other patch I might be missing for the 3.16 kernel?
> 
> Cheers,
> Luís

**Comment by philmmanjaro** [comment]
All needed patches are available or already added to all kernels.
