### ISSUE TITLE
procps-ng overlay still needed ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-core#120]
For a while already I have been seeing this message in boxit:
```
[OVERWRITTEN SYNC PACKAGE]  ->  [LOCAL PACKAGE]

   procps-ng-3.3.12-3-x86_64.pkg.tar.xz  ->  procps-ng-3.3.12-2.1-x86_64.pkg.tar.xz
```
@jonathonf can this overlay be removed?

**Comment by jonathonf** [comment]
The overlay is needed for Manjaro-side customisations of the default toprc. This returns `top` to some semblance of usefulness-by-default instead of the blood-red tree view.

**Comment by jonathonf** [comment]
I've updated to 3.3.13-0; this will notify when Arch update too, and we can edit our PKGBUILD from there.

**Comment by oberon2007** [comment]
Not sure if I was clear. When we have a pkg **3.3.13-0** boxit will complain already when Arch pushes **3.3.13-1**, which isn't when we actually need to update our pkg.
If you would have versioned our pkg **3.3.13-1** we'd ne notified once Arch releases **3.3.13-2** or **3.3.14-1**, which is what we want, I guess.

**Comment by jonathonf** [comment]
At the point I packaged 3.3.13-0, Arch was still on 3.3.12-3, so I did want to be notified about upstream's 3.3.13-1.

**Comment by oberon2007** [comment]
I don't understand. What are you going to do when Arch pushes 3.3.13-1 ?

**Comment by jonathonf** [comment]
When Arch pushed 3.3.13-1, I checked what changed they made to their PKGBUILD, merged them with ours, and rebuilt as 3.3.13-1.1 to include our customisations.

**Comment by oberon2007** [comment]
I see. It's just less ideal that, in case there's no need for a rebuild, we keep gettings notifications about newer updstream until the following update, like it was this time...

**Comment by oberon2007** [comment]
Actually, no.
Current situation is:
```
:: 1 overwritten sync package(s) are newer than local package(s) in repository core x86_64!
   Continue? [Y/n/d] (d=details) d

newer overwritten sync packages:

   [OVERWRITTEN SYNC PACKAGE]  ->  [LOCAL PACKAGE]

   procps-ng-3.3.13-1-x86_64.pkg.tar.xz  ->  procps-ng-3.3.13-0-x86_64.pkg.tar.xz

:: 3 overwritten sync package(s) are newer than local package(s) in repository extra x86_64!
   Continue? [Y/n/d] (d=details) d

newer overwritten sync packages:

   [OVERWRITTEN SYNC PACKAGE]  ->  [LOCAL PACKAGE]

   intel-ucode-20180312-1-any.pkg.tar.xz  ->  intel-ucode-20180312-0-any.pkg.tar.xz
   mono-addins-1.3.3-1-x86_64.pkg.tar.xz  ->  mono-addins-1.1-1-x86_64.pkg.tar.xz
   powerdevil-5.12.4-1-x86_64.pkg.tar.xz  ->  powerdevil-5.12.1-1.1-x86_64.pkg.tar.xz
```
If it were all overlay packages, the list would be long. I think atm there are some reasons why @philmmanjaro hasn't updated those three pkg, but normally when I see a pkg listed here, it is an indicator that something needs to be done about it.
Well, if I know that is how you want to handle **procps-ng** I will just ignore the notification...

**Comment by oberon2007** [comment]
I guess normally we just wait until upstream updates and then we package our overlay with the higher pkgrel - with the exception of when Arch lags behind a long, like it was sometimes the case with Cinnamon pkgs...

**Comment by philmmanjaro** [comment]
All packages we have overlay packages for the release version doesn't matter. The user won't see them. We only have to have numbers like 1.1 when we added a package after we had the upstream package before and on overlay on our end. When we build the packages on our own, we should blacklist the same from Arch so we don't sync them anymore.
