### ISSUE TITLE
417: Kpanic-like driver errors

### ISSUE THREAD

**Issue by bn0785ac** [manjaro/packages-core#124]
Hard:

* Mobo: Asus m5a78
* CPU: FX 8350-4.1 (safe temps, safe volts)
* GPU: RX 560-2 (asus)
* 417 =.r180418.a27fc14

Logs
https://u.teknik.io/fQDZD.txt

**Comment by jonathonf** [comment]
This is not a packaging issue.

4.17 is a pre-release kernel.
