### ISSUE TITLE
[filesystem] ERROR: hostname was not found in the build directory and is not a URL.

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-core#126]
https://github.com/manjaro/packages-core/blob/0e1f8cee84898fa641a88468012659250b5a3de4/filesystem/PKGBUILD#L20

The `hostname` file is missing from the available sources.

**Comment by philmmanjaro** [comment]
fixed via 6ba18748aba71e4b0fc15234c63daa6f106eac63
