### ISSUE TITLE
Procps-ng 3.3.15 breaks deepin system monitor package built against procps-ng 3.3.14

### ISSUE THREAD

**Issue by FredBezies** [manjaro/packages-core#130]
As I'm using Manjaro Deepin with testing repositories enabled, I noticed deepin-system-monitor is broken.

It search for /usr/lib/libprocps.so.6 but procps-ng 3.3.15 provides /usr/lib/libprocps.so.7!

Annoying :(

Opened a thread on manjaro.org forum.

https://forum.manjaro.org/t/deepin-testing-system-monitor-needs-to-be-rebuild-against-procps-ng-3-3-15-1-0/48092

Of course, after rebuilding deepin-system-monitor against new procps-ng, everything worked back.

**Comment by FredBezies** [comment]
Not to forget 39 others packages depending in a way or another of procps-ng.

https://www.archlinux.org/packages/core/x86_64/procps-ng/

**Comment by oberon2007** [comment]
Seems we have a problem here when **procps-ng** is out of sync with Arch upstream pkgs. @jonathonf

**Comment by jonathonf** [comment]
3.3.15 included a library soname increment along with various CVE fixes.

I've uploaded 3.3.14-1.2 which backports the fixes, https://github.com/manjaro/packages-core/commit/1fe95804d419b10346370a823030eb1cd3eae04d

**Comment by FredBezies** [comment]
Ok. Thanks for the fix.
