### ISSUE TITLE
[linux41] Kernel panic at i686

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#14]
Beginning with linux41 on i686 boot up crashes - kernel panic :
![img_20150625_221002](https://cloud.githubusercontent.com/assets/5050022/8364609/c574d16a-1b87-11e5-80b3-98c208bc5873.jpg)

**Comment by philmmanjaro** [comment]
Build was done with AMD-CPU and **manjaro-tools r1411.9a00d6e-1**.

```                                      
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: X86-64
  Vendor: "AuthenticAMD"
  Model: 16.2.3 "AMD Phenom(tm) 9650 Quad-Core Processor"
  Features: fpu,vme,de,pse,tsc,msr,pae,mce,cx8,apic,sep,mtrr,pge,mca,cmov,pat,pse36,clflush,mmx,fxsr,sse,sse2,ht,syscall,nx,mmxext,fxsr_opt,pdpe1gb,rdtscp,lm,3dnowext,3dnow,constant_tsc,rep_good,nopl,nonstop_tsc,extd_apicid,pni,monitor,cx16,popcnt,lahf_lm,cmp_legacy,svm,extapic,cr8_legacy,abm,sse4a,misalignsse,3dnowprefetch,osvw,ibs,hw_pstate,npt,lbrv,svm_lock,vmmcall
  Clock: 1150 MHz
  BogoMips: 4600.05
  Cache: 512 kb
  Units/Processor: 4
  Config Status: cfg=new, avail=yes, need=no, active=unknown

```

**Comment by philmmanjaro** [comment]
Maybe somebody might build [linux41](https://github.com/manjaro/packages-core/tree/master/linux41) on a different CPU and link me the packages, so I might test it on my machine ...

**Comment by Kirek** [comment]
Here you go, boots in a vm
https://www.dropbox.com/s/4i18j3ddvbdjxg4/linux41-4.1.0-0-i686.pkg.tar.xz?dl=0
https://www.dropbox.com/s/1x6k8cwfxk8vzx2/linux41-headers-4.1.0-0-i686.pkg.tar.xz?dl=0

**Comment by philmmanjaro** [comment]
@Kirek, thx for building. Your build also crashes on my end on real hardware. If possible, can you check your build and mine from the repos, if those boot up on your end. Seems there is a regression with AMD CPUs and that kernel series, at least with i686.

**Comment by Kirek** [comment]
rc8 from the repos works fine too

**Comment by philmmanjaro** [comment]
Well, seems to be my CPU then. That means I have to wait until upstream will fix it ...

**Comment by Kirek** [comment]
Is this solved with 4.1.1 ?

**Comment by philmmanjaro** [comment]
No, still there. I think that is why Arch is not updating their **linux** package to that series yet.

**Comment by philmmanjaro** [comment]
So. still no good news from my end also 4.1.2 fails to boot on my CPU in i686. **linux40** will be marked EOL with 4.0.9.

**Comment by korrode** [comment]
This probably isn't it, but have you checked that the initrd line for the Grub entry is indeed correct?

i.e.
initrd /boot/intel-ucode.img /boot/initramfs-4.1-i686.img

**Comment by philmmanjaro** [comment]
Well, this one is correct:
<pre>linux /boot/vmlinuz-4.1-i686 root=UUID=8f9e56bc-917c-4022-a19d-2d1b6afe8731 rw resume=UUID=ba2e00a7-b715-40a4-922b-982f01126ae1 quiet splash
initrd /boot/intel-ucode.img /boot/initramfs-4.1-i686.img
</pre>

Might check it without ucode to see ...

**Comment by philmmanjaro** [comment]
**4.1.3** still doesn't boot for me in **i686**.

**Comment by philmmanjaro** [comment]
Testing with archiso has to wait a little ...
Current Release: 2015.07.01
Included Kernel: 4.0.7

**Comment by philmmanjaro** [comment]
However, I can boot the kernel in VirtualBox:
<pre>[johnd@john-pc Desktop]$ uname -a
Linux john-pc 4.1.3-1-MANJARO #1 SMP PREEMPT Wed Jul 22 19:01:09 UTC 2015 i686 GNU/Linux
[johnd@john-pc Desktop]$ hwinfo --cpu
01: None 00.0: 10103 CPU                                        
  [Created at cpu.457]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: Intel
  Vendor: "AuthenticAMD"
  Model: 16.2.3 "AMD Phenom(tm) 9650 Quad-Core Processor"
  Features: fpu,vme,de,pse,tsc,msr,pae,mce,cx8,apic,sep,mtrr,pge,mca,cmov,pat,pse36,clflush,mmx,fxsr,sse,sse2,syscall,nx,mmxext,fxsr_opt,rdtscp,lm,3dnowext,3dnow,rep_good,extd_apicid,pni,monitor,cx16,popcnt,lahf_lm,cr8_legacy,abm,sse4a,misalignsse,3dnowprefetch,vmmcall
  Clock: 2300 MHz
  BogoMips: 4599.48
  Cache: 512 kb
  Config Status: cfg=new, avail=yes, need=no, active=unknown
</pre>

However, using more than one core will create the crash also.

**Comment by philmmanjaro** [comment]
Here we go for the screenshots:

![vlcsnap-2015-07-23-22h49m16s725](https://cloud.githubusercontent.com/assets/5050022/8862072/3f5aaa1a-318e-11e5-9cf4-88f6d4b58736.png)

![vlcsnap-2015-07-23-22h56m21s038](https://cloud.githubusercontent.com/assets/5050022/8862075/46d95926-318e-11e5-99b0-fbe689631053.png)

![vlcsnap-2015-07-23-22h50m40s608](https://cloud.githubusercontent.com/assets/5050022/8862080/4e1f3a34-318e-11e5-91bc-8e5d958243bf.png)

**Comment by philmmanjaro** [comment]
Some of the text:

<pre>Failed to access perfctr msr (MSR c0010007 is 0)

task: f58e0000 ti: f58e8000 task.ti: f58e800
EIP: 0060:[<c135a903>] EFLAGS: 00010206 CPU: 0
EIP is at free_cache_attributes+0x83/0xd0
EAX: 00000001 EBX: f589d46c ECX: 00000090 EDX: 360c2000
ESI: 00000000 EDI: c1724a80 EBP: f58e9ec0 ESP: f58e9ea0
 DS: 007b ES: 007b FS: 00d8 GS: 00e0 SS: 0068
CR0: 8005003b CR2: 000000ac CR3: 01731000 CR4: 000006d0</pre>

**Comment by groeck** [comment]
The best way to get this fixed would be to bisect the problem.

**Comment by philmmanjaro** [comment]
Well, this might take a while, as I've to find the entry first, if any 4.1-rcX boot up at all with this setting.

**Comment by philmmanjaro** [comment]
I just tested 4.2-rc3 from [arch.miffe.org](http://arch.miffe.org/i686/). Same issue with more than one CPU core in i686. However it says: **Failed to find cpu0 device node** when booting up as single-core.

**Comment by groeck** [comment]
On 07/23/2015 10:43 PM, Philip Müller wrote:
> I just tested 4.2-rc3 from arch.miffe.org <http://arch.miffe.org/i686/>. Same issue with more than one CPU core in i686. However it says: *Failed to find cpu0 device node* when booting up as single-core.
>

The cpu node message is just noise.

Guenter

**Comment by philmmanjaro** [comment]
So, I just tested mainline 4.1-rc1 to 4.1-rc8 on a Xubuntu 15.04 VirtualBox install with two CPU cores enabled. Guess what, all kernels booted up. Also 4.2-rc3 booted just fine in that virtual machine. Might be configs then?

**Comment by philmmanjaro** [comment]
I now compared our config against [Ubuntus](https://gist.github.com/philmmanjaro/050790a50fd25309c06e) and against [x86_64](https://gist.github.com/philmmanjaro/d0d5720e4a642bee9083). Both boot somehow. Still don't get which module is affected, though.

**Comment by philmmanjaro** [comment]
Ok, seems to be a **config** issue. Using Ubuntus config made it boot on my machine. However it created a 1 GB package in size. Some of the differences made it boot after all. Also x86_64 boots. I'll try to check now what blocks it on my end to boot on i686.

**Comment by groeck** [comment]
On 07/24/2015 03:11 PM, Philip Müller wrote:
> Ok, seems to be a *config* issue. Using Ubuntus config made it boot on my machine. However it created a 1 GB package in size. Some of the differences made it boot after all. Also x86_64 boots. I'll try to check now what blocks it on my end to boot on i686.
>

Getting somewhere. Maybe it is just a change in configuration parameters.

Bisect with the original configuration might be useful, though,
to help understand what change is causing the problem with that configuration.

Thanks,
Guenter

**Comment by philmmanjaro** [comment]
Well, I still can't pin-point which of these settings are needed. I assume it has something with CPU section to do. How should I Bisect?

**Comment by groeck** [comment]
On 07/24/2015 04:31 PM, Philip Müller wrote:
> Well, I still can't pin-point which of these settings are needed. I assume it has something with CPU section to do. How should I Bisect?
>

Presumably you know a working kernel version. It should be a mainline kernel,
for example 4.0. You also know a broken kernel, for example 4.1.

Pick the latest kernel known to work and the earliest broken kernel
you can find. From a cloned mainline kernel tree, run

git bisect start <broken> <good>

With the example above, that would be

git bisect start 4.1 4.0

Build the image with the resulting version, and test it.
If it is good, enter
	git bisect good
otherwise enter
	git bisect bad

After several iterations (around 12-14) it will (hopefully) tell you
the offending commit. Run "git bisect log" and post the results, and
"git bisect reset" to finish the bisect and clean up the tree.

Hope this helps, and that I understood your question correctly.

Guenter

**Comment by philmmanjaro** [comment]
Well, we know that the Ubuntu config somehow boot. We also know that 4.0 boots also fine. So it has something to do with configuration. [Here](https://gist.github.com/philmmanjaro/700078605d78bfbdb5b6) are the differences from 4.0 > 4.1. I'm now comparing them with those from Ubuntu. I tried some different settings already but still couldn't boot. I'll take a look at bisect when I've an entry found which doesn't boot.

**Comment by groeck** [comment]
On 07/24/2015 11:27 PM, Philip Müller wrote:
> Well, we know that the Ubuntu config somehow boot. We also know that 4.0 boots also fine. So it has something to do with configuration. Here <https://gist.github.com/philmmanjaro/700078605d78bfbdb5b6> are the differences from 4.0 > 4.1. I'm now comparing them with those from Ubuntu. I tried some different settings already but still couldn't boot. I'll take a look at bisect when I've an entry found which doesn't boot.
>

You would have to run the 4.0 configuration through "make oldnoconfig"
or better "make olddefconfig" to have a useful comparison.

Guenter

**Comment by philmmanjaro** [comment]
Well, currently I'm building [4.1-rc1](https://github.com/philmmanjaro/linux41) using the "final" 4.1.1 config as base. I simply want to see if that will even boot in the current settings. olddefconfig I'll check later, if that test fails. As 4.2 is also affected on my end I've to find this stupied issue. I still wonder why the Ubuntu config worked but created this huge kernel over 1 GB. Seems those configs don't play nice with those on Arch-based systems ;)

**Comment by philmmanjaro** [comment]
I see some progress now! [4.1-rc0-b5-7fd56474db](https://github.com/philmmanjaro/linux41/commit/4a8dec895c7d4863b32bb68ab2bfdb61b272f283) was the first **good** run out of 5. So the current bad one is [4.1-rc0-b4-1a370f4cd9](https://github.com/philmmanjaro/linux41/commit/6e61e9e488fd84ab1eacdfaa8e9820fefcf7ca3a). This also means it happend in early development cycle of 4.1-series. **165 revisions** left to test after this (roughly 7 steps, though) ...

**Comment by groeck** [comment]
On 07/25/2015 06:38 AM, Philip Müller wrote:
> I see some progress now! 4.1-rc0-b5-7fd56474db <https://github.com/philmmanjaro/linux41/commit/4a8dec895c7d4863b32bb68ab2bfdb61b272f283> was the first *good* run out of 5. So the current bad one is 4.1-rc0-b4-1a370f4cd9 <https://github.com/philmmanjaro/linux41/commit/6e61e9e488fd84ab1eacdfaa8e9820fefcf7ca3a>. This also means it happend in early development cycle of 4.1-series. *165 revisions* left to test after this (roughly 7 steps, though) ...
>

Getting somewhere. The range includes a number of x86 patches, so I think you are on the right track.

Guenter

**Comment by philmmanjaro** [comment]
Yes, the last builds are regarding x86 patches as you can follow in [this file](https://github.com/philmmanjaro/linux41/blob/master/git-bisect.txt). I'm pretty close now, roughly 3 steps, though ...

**Comment by philmmanjaro** [comment]
So, either it is [Pull x86 debug changes from Ingo Molnar:  "Stack printing fixlets"](https://github.com/torvalds/linux/commit/64f004a2ab68691b5a2e3db4cb460fcd31b6abc6) or [Pull x86 cacheinfo sysfs changes from Ingo Molnar:  "This tree converts the x86 cacheinfo sysfs code to use the generic
  code in drivers/base/cacheinfo.c](https://github.com/torvalds/linux/commit/b48488d10954e0a337c41ea2e6086f274f118acf), which I'm currently compiling.

**Comment by groeck** [comment]
On 07/25/2015 11:42 AM, Philip Müller wrote:
> So, either it is Pull x86 debug changes from Ingo Molnar: "Stack printing fixlets" <https://github.com/torvalds/linux/commit/64f004a2ab68691b5a2e3db4cb460fcd31b6abc6> or Pull x86 cacheinfo sysfs changes from Ingo Molnar: "This tree converts the x86 cacheinfo sysfs code to use the generic
> code in drivers/base/cacheinfo.c <https://github.com/torvalds/linux/commit/b48488d10954e0a337c41ea2e6086f274f118acf>, which I'm currently compiling.
>

I'd guess the latter, since it touches some AMD code.

Wonder if CONFIG_AMD_NB is defined in one of your configurations but not the other.

Guenter

**Comment by philmmanjaro** [comment]
Hmm. **bisect good 9f3252f** comes one commit before **bisect bad b48488d**. Both done on 13th of April. Why does **bisect** now suggest to do another run with [**cecae36**](https://github.com/torvalds/linux/commits/cecae360744d958c0af562e806dbd4632be13efc) from March? **CONFIG_AMD_NB=y** is set on both configs, also in that of **Ubuntu**, which also worked ...

**Comment by philmmanjaro** [comment]
If I compare those patches directly, the only difference is:
```
diff --git a/arch/x86/kernel/cpu/intel_cacheinfo.c b/arch/x86/kernel/cpu/intel_cacheinfo.c
index 8008bc2..edcb0e2 100644
--- a/arch/x86/kernel/cpu/intel_cacheinfo.c
+++ b/arch/x86/kernel/cpu/intel_cacheinfo.c
@@ -556,7 +556,7 @@ cache_get_priv_group(struct cacheinfo *this_leaf)
 {
 	struct amd_northbridge *nb = this_leaf->priv;
 
-	if (this_leaf->level < 3)
+	if (this_leaf->level < 3 || !nb)
 		return NULL;
 
 	if (nb && nb->l3_cache.indices)
```
I'll revert it now and try to build again **4.1.3**.

**Comment by philmmanjaro** [comment]
The little detour didn't paied out. Currently building **4.1rc0.b12.cecae36074**.

**Comment by groeck** [comment]
On 07/25/2015 12:28 PM, Philip Müller wrote:
> Hmm. *bisect good 9f3252f* comes one commit before *bisect bad b48488d*. Both done on 13th of April. Why does *bisect* now suggest to do another run with *cecae36* <https://github.com/torvalds/linux/commits/cecae360744d958c0af562e806dbd4632be13efc> from March? *CONFIG_AMD_NB=y* is set on both configs, also in that of *Ubuntu*, which also worked ...
>

Magic ;-). Those are all merges, so git now probably tries to bisect
into the patches pulled in from the merge.

Guenter

**Comment by philmmanjaro** [comment]
Yeah, magic! Logic tells me this:

Since [b48488d109](https://github.com/torvalds/linux/commits/b48488d10954e0a337c41ea2e6086f274f118acf) needs somehow modified for AMD, [cecae36074](https://github.com/torvalds/linux/commits/cecae360744d958c0af562e806dbd4632be13efc) and [0d55ba46bf](https://github.com/torvalds/linux/commits/0d55ba46bfbee64fd2b492b87bfe2ec172e7b056) are the same patches. So it originated with **Move cacheinfo sysfs code to generic infrastructure** by Sudeep Holla.

```
9f4189b631a6246f47f1903c9a6703d5  b48488d10954e0a337c41ea2e6086f274f118acf.patch
407be39d3b44702ccba50d1d09534b44  cecae360744d958c0af562e806dbd4632be13efc.patch
407be39d3b44702ccba50d1d09534b44  0d55ba46bfbee64fd2b492b87bfe2ec172e7b056.patch
```
Now we have to understand why only **i686** is affected by this and only if the **CPU cores** are **higher than 2**.

**Comment by philmmanjaro** [comment]
A discussion is also happening in our forums: [[linux41] does the i686 build work for you?](https://forum.manjaro.org/index.php?topic=24541.0). There we came thru tests by the community to the same conclusions. Upstream is now also [informed](http://www.spinics.net/lists/kernel/msg2041512.html). Lets see how we will fix this properly.

**Comment by philmmanjaro** [comment]
Upstream bug can be found here: [#101971 - Regression with 'x86/cacheinfo: Move cacheinfo sysfs code to generic infrastructure' on AMD i686](https://bugzilla.kernel.org/show_bug.cgi?id=101971)

**Comment by philmmanjaro** [comment]
Upstream development can be followed also [here](https://lkml.org/lkml/2015/7/23/825).

**Comment by philmmanjaro** [comment]
Finally it hit the [url=https://github.com/torvalds/linux/commit/2110d70c5e58326a10e93cfefdc0b3686e2ada12]linus tree[/url].

**Comment by philmmanjaro** [comment]
Finally made it upstream [4.2.4](https://lists.manjaro.org/pipermail/manjaro-dev/Week-of-Mon-20151012/000713.html), [4.1.11](https://lists.manjaro.org/pipermail/manjaro-dev/Week-of-Mon-20151012/000712.html)
