### ISSUE TITLE
[kernel41] not ready to run lxc

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-core#15]
~~~
$ sudo lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: missing
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
File capabilities: enabled
~~~

User Namespace support missing, but lxc-1.1.1 in the repos.

**Comment by philmmanjaro** [comment]
@udeved: Is this still relevant? If so, what do you need to have this one fixed?

**Comment by udeved** [comment]
The cgmanager part is fixed, not sure if the kxc script still points out kernel settings missing.

**Comment by philmmanjaro** [comment]
Due to security concerns, the Manjaro kernels do NOT ship with the ability to run containers as an unprivileged user; therefore, it is normal to see a missing status for "User namespaces" when running the check. See [FS#36969](https://bugs.archlinux.org/task/36969) for this feature request.
