### ISSUE TITLE
downgrade ncurses, bash and readline?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-core#16]
Should we replace those packages with the stable versions in testing and unstable until this issue is fixed?
https://forum.manjaro.org/index.php?topic=26301.msg223333#msg223333

**Comment by Kirek** [comment]
This problems are in testing, and in unstable should be already be fixed with latest upstream packages...

**Comment by oberon2007** [comment]
I ran into this problem in unstable!

**Comment by Kirek** [comment]
After this too? https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150914/004190.html

**Comment by oberon2007** [comment]
Hah! I ran my update 10 minutes before that obviously ... Trying again now. ;)

**Comment by Kirek** [comment]
Check that bash and readlines are in the third revision too.

**Comment by oberon2007** [comment]
I have those versions. But it's not fixed for me!

**Comment by oberon2007** [comment]
My systemd install works fine, but under openrc x doesn't start.

**Comment by oberon2007** [comment]
the name of my host =(none)

**Comment by Kirek** [comment]
It's possible that some openrc package need to be recompiled against new ncurses?

**Comment by Kirek** [comment]
Maybe openrc-core needs a rebuild against new ncurses:
https://github.com/manjaro/packages-openrc/blob/master/openrc-core/PKGBUILD#L71

**Comment by udeved** [comment]
@Kirek 

Not sure about rebuilding.
I didn't have to rebuild on gentoo, and they also had a borked ncurses update, which caused emerge to stop working.

**Comment by philmmanjaro** [comment]
The main issue was that my pull from the server wasn't finished. This might happen. I should have waited a little longer before pushing it to **testing**. Latest sync with Arch should fix it at least for **systemd** based systems. I recommend to rebuild **openrc-core** after all.

**Comment by philmmanjaro** [comment]
New packages are online, at least on our german server **Netzspielplatz**:
```
[New Packages]
bash-4.3.042-3-i686.pkg.tar.xz
readline-6.3.008-3-i686.pkg.tar.xz

[New Packages]
bash-4.3.042-3-x86_64.pkg.tar.xz
readline-6.3.008-3-x86_64.pkg.tar.xz
```

**Comment by udeved** [comment]
Rebuild is on the way to be on safe side.

**Comment by philmmanjaro** [comment]
After rebuild you can generate also a fresh openrc install media to be sure that everything is fine. I'll spin now a 15.12-dev anyway with systemd as Catalyst has some changes I've to test.

**Comment by udeved** [comment]
I am still not sure if this is really fixed.
Systemd isn't just as affected because it doesnt use a shell to boot.
But conky was reported to be still not working.
You can try on systemd by invoking gpg for example. bash will likely still throw a shared lib error, ie linking problem.

**Comment by philmmanjaro** [comment]
Not on my end:
```
[phil@manjaro Arbeitsfläche]$ gpg
gpg: Auf geht's - Botschaft eintippen ...
test
it
^C
gpg: signal Interrupt caught ... exiting
```

**Comment by udeved** [comment]
Hmm, everything fine if reinstalling base group?
Any errors? Its package specific.

**Comment by philmmanjaro** [comment]
I just updated my system. Nothing more. You know I'm running **systemd** here.

**Comment by udeved** [comment]
Yes, I know you run systemd, but the linking error is package specific, if readline or bash are involved.

I spent some time on gentoo to fix it before they provided a fix.

**Comment by philmmanjaro** [comment]
Well, I simply had bad timing with the sync-server. Those packages were not there, so the snap was incomplete. Now all needed packages are in place. Please do a testbuild of a **openrc** profile with the current packages in **unstable** or **testing** to be sure we have all issues solved by now.

**Comment by udeved** [comment]
What I am saying, I am not sure arch have properly fixed bash and readline yet in their testing.

**Comment by philmmanjaro** [comment]
**bash 4.3.042-3**
Add libncursesw.so sodep to prevent users from downgrading ncurses.

---

please perform a fresh build of a new install media to be sure. Anything else is just wasting time ...

**Comment by udeved** [comment]
I don't have time right now to do iso, sorry.
i am on the way out, just wanted to make sure the box boots with openrc, which it didn't due to failing shell.

**Comment by philmmanjaro** [comment]
Well, it should now. Maybe Bernhard find some time to spin an **openrc** profile ...

**Comment by oberon2007** [comment]
Can try that later tonight - I'm out right now, too. The quite recent fluxbox however still doesn't survive switching to unstable...

**Comment by udeved** [comment]
It boots fine with the pkgrel3 of bash and readline.
:beer:  now

**Comment by oberon2007** [comment]
Not a surprise but just to reconfirm: A freshly built i3-openrc boots without any problem. :)
