### ISSUE TITLE
linux41- 4.1.8-2

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-core#17]
aufs4.1-20150921.patch.bz2 mssing
Doesn't build

~~~
==> Empfange Quellen...
  -> linux-4.1.tar.xz gefunden
  -> patch-4.1.8.xz gefunden
  -> config gefunden
  -> config.x86_64 gefunden
  -> config.aufs gefunden
  -> linux41.preset gefunden
==> FEHLER: aufs4.1-20150921.patch.bz2 wurde nicht im build Verzeichnis gefunden und ist keine URL.
~~~

**Comment by philmmanjaro** [comment]
Fixed with 1d66521a20c0855191543cab968b1e977775bb64

**Comment by udeved** [comment]
There is another flaw, the kernel config is messed up, no matter what config ui you set, the kernel want to be manually configured before ui is run.

**Comment by philmmanjaro** [comment]
Well, I didn't build this kernel yet. I assume the config files need a run with **makepkg** and then a checksum update with **updpkgsums**. This is just a note to myself to include it in our next build.

**Comment by philmmanjaro** [comment]
I just checked with **x86_64**. Don't see any issues regarding configs. Be more specific:
```
  UPD     include/generated/bounds.h
  UPD     include/generated/timeconst.h
  CC      arch/x86/kernel/asm-offsets.s
  CHK     include/generated/asm-offsets.h
  UPD     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
==> Beginne build()...
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  HOSTCC  scripts/kallsyms
  CC      scripts/mod/empty.o
```

**Comment by udeved** [comment]
Its as if there is no make oldconfig run.
The build start with tons of new stuff to set.

**Comment by philmmanjaro** [comment]
Which **architecture**?

**Comment by udeved** [comment]
x86_64

**Comment by philmmanjaro** [comment]
Well, try again, as I did it just minutes ago. Maybe post your output on what should be reconfigured. Then you may compare it with the created config file.
