### ISSUE TITLE
[shutdown] Cgroup : option or name mismatch , new:0x0 '''', old:0x4 "systemd" Shutdown[1]: failed to finalize file systems , ignoring

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#18]
Reported by محمد صبحي قباني by e-mail:

Trying to shutdown results in `Cgroup : option or name mismatch , new:0x0 '''', old:0x4 "systemd"
Shutdown[1]: failed to finalize file systems , ignoring`

![p_ _](https://cloud.githubusercontent.com/assets/5050022/10301520/8b2759a2-6c03-11e5-8896-cc31d2fbdeb0.jpg)

Similar issues already posted at:

[[arch] cgroup : option or name mismatch, new: 0x0"", old: 0x4 "systemd"](https://bbs.archlinux.org/viewtopic.php?id=174979)
[[arch] [systemd mkinitcpio ] New weird messages during shutdown after upgrade](https://bbs.archlinux.org/viewtopic.php?pid=1362098)
[[cup of linux] Has any of you experienced trouble like this?](http://www.cupoflinux.com/SBB/index.php?topic=2771.0)
[[manjaro] Startup error and shutdown hang.](https://forum.manjaro.org/index.php?topic=11698.0)

**Comment by estebanprimost** [comment]
I have the same issue, but no "cgroup" error message is shown, just "Failed to finalize file systems". Any solution?.
Sorry for my english.

**Comment by philmmanjaro** [comment]
@estebanprimost: which kernel do you use?

**Comment by estebanprimost** [comment]
@philmmanjaro, here is my info:
OS: **Manjaro 15.12 Capella**
Kernel: **x86_64 Linux 4.5.0-2-MANJARO**

I see that this bug occurs when I'm using the laptop for a long time (from 2 to 4 hs, aprox).

**Comment by Biogent** [comment]
Everyone who has the same issue can upgrade kernel to >=4.6. This issue seems to be solved.

**Comment by estebanprimost** [comment]
Solved with kernel >= 4.6, as @Biogent says.

**Comment by pseudogeek** [comment]
not for me...
with kernel 4.6 in addiction i got a watchdog warning (watchdog not installed)

**Comment by Biogent** [comment]
@pseudogeek So, what error do you have? `watchdog watchdog0: watchdog did not stop!` and `Shutdown[1]: failed to finalize file systems , ignoring`?

**Comment by pseudogeek** [comment]
yes, that error: 'watchdog watchdog0: watchdog did not stop!' and 'Shutdown[1]: failed to finalize file systems , ignoring'.  I'm using 4.4.13-1 Manjaro kernel
my HW now is Lenovo X1 Carbon gen3 (2015) Legacy BIOS, no WIN on this disk, the original disk is having Win 7 but was removed
same error 'Shutdown[1]: failed to finalize file systems , ignoring' on other machine Dell Precision M 4800 2014, but now I'm out and I cannot try kernel 4.6 on that machine

**Comment by Biogent** [comment]
@pseudogeek What about shutdown and reboot process? Do you have hangs or freezes during this or just warnings and normal shutdown and reboot? Also, please, try use `poweroff` command in terminal and tell me warning are present or not?

**Comment by pseudogeek** [comment]
just waning and normal shutdown and reboot
using terminal to shutdown or reboot 'Shutdown[1]: failed to finalize file systems , ignoring' is still there

**Comment by Biogent** [comment]
@pseudogeek Seems to be **systemd** problem, not kernel. Let's another try to fix it :)
Do you have external USB storage? Also good idea (in order to make sure that it's really not kernel issue) to try install older kernel `sudo mhwd-kernel -i linux312`. Print your `/etc/fstab` there.

In general, try to do so:
1. Change/Add in `/etc/systemd/system.conf` the following settings
`DefaultTimeoutStartSec=3s
DefaultTimeoutStopSec=3s
TimeoutSec=3s`
Shutdown/Reboot and feedback is warning still present or not.
2. If warning still present than `sudo mhwd-kernel -i linux312`, boot with linux312 and check shutdown/reboot.
3. Also don't forget to print `/etc/fstab` there.

**Comment by pseudogeek** [comment]
I check today, I'm having UEFI BIOS set with Legacy BIOS first
yes, must be a systemd problem started with 226
1) still present
2) this machine not suppose to work with kernel < 4.0

thanks for your effort, anyway this bug doesn't seems to create problems to my installation, everything works fine

**Comment by Biogent** [comment]
@pseudogeek hope this warning will be solved in the nearest systemd build. You also try to reinstall with UEFI support (not Legacy). Also try `rmmod xhci_pci && shutdown -h now` in terminal.
@philmmanjaro It seems to be close this issue. The system no longer hangs, only warnings.

**Comment by pseudogeek** [comment]
Sorry for late...
the issue seems solved with kernel 4.8 onward on both my machines.
