### ISSUE TITLE
AMD Radeon GPU Acceleration Disabled Under Kernels 4.2.x and Later.

### ISSUE THREAD

**Issue by overclockedoncoffee** [manjaro/packages-core#20]
I'm seeing a bug of some sort which is causing mesa to fallback to software rendering (llvmpipe) if  i'm using any kernel 4.2.x or above.

My GPU is an AMD Radeon 7770, and if i boot using kernel 3.19.x or 4.1.x, mesa utilizes the radeonsi driver, providing openGL 4.1 core profile, OpenGL 3.0, and OpenGLES 3.0. If, however, i boot up any kernel 4.2 or higher, mesa uses the llvmpipe software rasterizer.

I'd thought it was a firmware issue, with the linux-firmware package perhaps not having been updated to support the latest kernels, but even when I installed linux-firmware-git from the AUR to replace the standard linux-firmware package and then booted linux 4.3-rc7, mesa was still using llvmpipe instead of radeonsi. Pwering down the computer and booting linux 3.19.8 or 4.1.11 instead of 4.3-rc7 does get radeonsi to be used correctly, but I'd like to not be stuck on this kernel because I can't obtain 3D acceleration on new kernels.

The Xorg.0.log after booting kernel 4.3 contains the following:
[     4.591] (II) [KMS] Kernel modesetting enabled.
[     4.591] (II) RADEON(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[     4.591] (==) RADEON(0): Depth 24, (--) framebuffer bpp 32
[     4.591] (II) RADEON(0): Pixel depth = 24 bits stored in 4 bytes (32 bpp pixmaps)
[     4.591] (==) RADEON(0): Default visual is TrueColor
[     4.591] (==) RADEON(0): RGB weight 888
[     4.591] (II) RADEON(0): Using 8 bits per RGB (8 bit DAC)
[     4.591] (--) RADEON(0): Chipset: "VERDE" (ChipID = 0x683d)
[     4.591] (II) RADEON(0): GPU accel disabled or not working, using shadowfb for KMS
[     4.591] (II) Loading sub module "shadow"
[     4.591] (II) LoadModule: "shadow"
[     4.591] (II) Loading /usr/lib/xorg/modules/libshadow.so
[     4.592] (II) Module shadow: vendor="X.Org Foundation"

However, Xorg.0.log after I boot kernel 4.1.11 shows that under that kernel, the proper dri driver is active:
[     4.662] (II) [KMS] Kernel modesetting enabled.
[     4.662] (II) RADEON(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[     4.662] (==) RADEON(0): Depth 24, (--) framebuffer bpp 32
[     4.662] (II) RADEON(0): Pixel depth = 24 bits stored in 4 bytes (32 bpp pixmaps)
[     4.662] (==) RADEON(0): Default visual is TrueColor
[     4.662] (==) RADEON(0): RGB weight 888
[     4.662] (II) RADEON(0): Using 8 bits per RGB (8 bit DAC)
[     4.662] (--) RADEON(0): Chipset: "VERDE" (ChipID = 0x683d)
[     4.662] (II) Loading sub module "dri2"
[     4.662] (II) LoadModule: "dri2"
[     4.662] (II) Module "dri2" already built-in
[     4.662] (II) Loading sub module "glamoregl"
[     4.662] (II) LoadModule: "glamoregl"
[     4.662] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[     4.672] (II) Module glamoregl: vendor="X.Org Foundation"
[     4.672] 	compiled for 1.17.2, module version = 1.0.0
[     4.672] 	ABI class: X.Org ANSI C Emulation, version 0.4
[     4.672] (II) glamor: OpenGL accelerated X.org driver based.

The complete dmesgs, Xorg.0.logs, and list of (could-be) relevant installed packages are available upon request in text file format, as the website says "Attaching documents requires permission to this repository." I can pastebin as needed to view log/s.

**Comment by philmmanjaro** [comment]
Well, with **4.2+** AMD pushed even more [AMDGPU](https://www.phoronix.com/scan.php?page=search&q=AMDGPU) code into the kernel, which is still half done. It might settle down with the upcoming **4.4 LTS** kernel. AMD is slow in developing. That is why they just recommend kernels not higher than **3.19** as of now.

**Comment by philmmanjaro** [comment]
With Linux 4.2 the **AMDGPU DRM** driver is part of the mainline kernel while the changes needed to **Mesa** and **libdrm** remain in branched repositories. There's also the new **xf86-video-amdgpu** DDX that's needed with **xf86-video-ati** not supporting the new kernel driver.

**Comment by overclockedoncoffee** [comment]
See http://pastebin.com/WQrwBspM. I asked in the #radeon irc channel and one of their members noticed something I didn't.

The relevent section of the dmesg from kernel 4.3-rc-7 indicates the driver is failing on the "drm:r600_ringtest"...but the card should be utilizing the radeonsi dri driver, NOT the r600 dri driver. Could the drm module or libdrm be prompting mesa to load the wrong dri driver?

2.558871] [drm] radeon: irq initialized.[    3.340560] [drm:r600_ring_test [radeon]] *ERROR* radeon: ring 0 test failed (scratch(0x850C)=0xCAFEDEAD)
[    3.340564] radeon 0000:01:00.0: disabling GPU acceleration

**Comment by philmmanjaro** [comment]
Interesting. I'm currently building the final **4.3.0** kernel. It might have been fixed there. Else we have to report it upstream and see if there is any problem solution soon.

**Comment by overclockedoncoffee** [comment]
I built a kernel using the 4.3.0 tarball directly from kernel.org, and an ubuntu default kernel config file. When I booted into the 4.3 kernel, GPU acceleration was still disabled. As neither the source nor the kernel config were from Manjaro, this rules out a distro bug. This looks as if it's upstream to me.

**Comment by philmmanjaro** [comment]
Please contact Alex Deucher (alexander.deucher.amd.com) from AMD and describe him your issue in rich detail. Maybe he understands and point you into a direction we can tackle your issue ...

**Comment by overclockedoncoffee** [comment]
I've already reported it upstream, and I'm attempting to git bisect to see exctly which commit broke my card. See https://bugs.freedesktop.org/show_bug.cgi?id=92858.

**Comment by philmmanjaro** [comment]
We have to find a kernel version which works for you. Then we have to find a kernel version you assume is the first broken one. A **git-bisect** may take between 10 to 14 hours, depending on your CPU and how you test your compiles. You can take a look at my [git-bisect of linux41](https://github.com/philmmanjaro/linux41) to have some overview how long it took for me.

**Comment by overclockedoncoffee** [comment]
It seems I've hit a snag. I started by bisecting the entire kernel between 4.1 and 4.2, using the command "git bisect start v4.2 v4.1" as per instructions from Christina Konig in his reply to my bug report at freedesktop.org. Everything went well until I reached a commig [c5fd936e992dd2829167d2adc63e151675ca6898] drm/nouveau: Pause between setting gpu to D3hot and cutting the power
git bisect bad c5fd936e992dd2829167d2adc63e151675ca6898

Any kernel I built after I told git bisect the above revision was bad froze on "loading initial ramdisk." I cleaned my source tree and rebuilt the kernel several times to no avail. I updated my bug report and Christian provided a useful tip "That's unfortunate but happens sometimes. Since c5fd936e992dd2829167d2adc63e151675ca6898 is bad the problem must be somewhere between v4.1 and c5fd936e992dd2829167d2adc63e151675ca6898. Since it is a radeon driver problem I suggest you limit bisect to only test the changes made to radeon. Please try the command "git bisect start c5fd936e992dd2829167d2adc63e151675ca6898 v4.1 drivers/gpu/drm/radeon/".

This helped, at least to compile and boot one kernel.
I told git bisect it was a good revision: # good: [c65b99f046843d2455aa231747b5a07a999a9f3d] Linux 4.1-rc6
git bisect good c65b99f046843d2455aa231747b5a07a999a9f3d
and proceeded to compile the kernel with the next commit that git bisect jumped to, commit d55a43a3e9258c01a6cac2f3081b3ceaa8e58020. That kernel compiled, though the folder the "make modules_install' command built was called linux-4.1.0-rc4 instead of -rc6 like the previous. 

And boom...freezing on 'loading initial ramdisk' yet again. There were about 21 commits left to check, so I played the odds that that one wasn't the bad commit and ran 'git bisect skip' to skip it and force bisect to move to another commit. Compiled the kernel again, and that one also failed to boot at "loading initial ramdisk." In an attempt to resolve, I've ran 'make localyesconfig' to compile in support for all my devices into the kernel, so technicially no initial ramdisk should even be needed. I've swapped ina default linux-4.3 default ubuntu kernel config file, and used 'zcat /proc/config > .config" to copy the running kernel's configs from both the 4.1.12 and 4.3.0 stock Manjaro kernels. I've added "systemd' to my HOOKS in mkinitcpio.conf in the event the initial ramdisk needed systemd support. Still nothing but a freeze at boot, on 'loading initial ramdisk.' Should I keep skipping over commits and compiling kernels until I can compile one that actually boots, or is there something I'm overlooking here that's needed that the stock Manjaro kernel configs don't provide and neither does the Ubuntu one. I'm using the instructions from https://wiki.archlinux.org/index.php/Kernels/Compilation/Traditional, and until hitting that one commit and then running into the same problem later when restricting the bisect to drivers/gpu/drm/radeon, it worked and the kernels I compiled booted up correctly.

**Comment by overclockedoncoffee** [comment]
It seems I've hit a snag. I started by bisecting the entire kernel between 4.1 and 4.2, using the command "git bisect start v4.2 v4.1" as per instructions from Christian Konig in his reply to my bug report #92858 at bugs.freedesktop.org. Everything went well until I reached a commig [c5fd936e992dd2829167d2adc63e151675ca6898] drm/nouveau: Pause between setting gpu to D3hot and cutting the power
git bisect bad c5fd936e992dd2829167d2adc63e151675ca6898

Any kernel I built after I told git bisect the above revision was bad froze on "loading initial ramdisk." I cleaned my source tree and rebuilt the kernel several times to no avail. I updated my bug report and Christian provided a useful tip "That's unfortunate but happens sometimes. Since c5fd936e992dd2829167d2adc63e151675ca6898 is bad the problem must be somewhere between v4.1 and c5fd936e992dd2829167d2adc63e151675ca6898. Since it is a radeon driver problem I suggest you limit bisect to only test the changes made to radeon. Please try the command "git bisect start c5fd936e992dd2829167d2adc63e151675ca6898 v4.1 drivers/gpu/drm/radeon/".

This helped, at least to compile and boot one kernel.
I told git bisect it was a good revision: # good: [c65b99f046843d2455aa231747b5a07a999a9f3d] Linux 4.1-rc6
git bisect good c65b99f046843d2455aa231747b5a07a999a9f3d
and proceeded to compile the kernel with the next commit that git bisect jumped to, commit d55a43a3e9258c01a6cac2f3081b3ceaa8e58020. That kernel compiled, though the folder the "make modules_install' command built was called linux-4.1.0-rc4 instead of -rc6 like the previous. 

And boom...freezing on 'loading initial ramdisk' yet again. There were about 21 commits left to check, so I played the odds that that one wasn't the bad commit and ran 'git bisect skip' to skip it and force bisect to move to another commit. Compiled the kernel again, and that one also failed to boot at "loading initial ramdisk." In an attempt to resolve, I've ran 'make localyesconfig' to compile in support for all my devices into the kernel, so technicially no initial ramdisk should even be needed. I've swapped ina default linux-4.3 default ubuntu kernel config file, and used 'zcat /proc/config > .config" to copy the running kernel's configs from both the 4.1.12 and 4.3.0 stock Manjaro kernels. I've added "systemd' to my HOOKS in mkinitcpio.conf in the event the initial ramdisk needed systemd support. Still nothing but a freeze at boot, on 'loading initial ramdisk.' Should I keep skipping over commits and compiling kernels until I can compile one that actually boots, or is there something I'm overlooking here that's needed that the stock Manjaro kernel configs don't provide and neither does the Ubuntu one. I'm using the instructions from https://wiki.archlinux.org/index.php/Kernels/Compilation/Traditional, and until hitting that one commit and then running into the same problem later when restricting the bisect to drivers/gpu/drm/radeon, it worked and the kernels I compiled booted up correctly.

**Comment by overclockedoncoffee** [comment]
It seems I've hit a snag. I started by bisecting the entire kernel between 4.1 and 4.2, using the command "git bisect start v4.2 v4.1" as per instructions from Christina Konig in his reply to my bug report at freedesktop.org. Everything went well until I reached a commig [c5fd936e992dd2829167d2adc63e151675ca6898] drm/nouveau: Pause between setting gpu to D3hot and cutting the power
git bisect bad c5fd936e992dd2829167d2adc63e151675ca6898

Any kernel I built after I told git bisect the above revision was bad froze on "loading initial ramdisk." I cleaned my source tree and rebuilt the kernel several times to no avail. I updated my bug report and Christian provided a useful tip "That's unfortunate but happens sometimes. Since c5fd936e992dd2829167d2adc63e151675ca6898 is bad the problem must be somewhere between v4.1 and c5fd936e992dd2829167d2adc63e151675ca6898. Since it is a radeon driver problem I suggest you limit bisect to only test the changes made to radeon. Please try the command "git bisect start c5fd936e992dd2829167d2adc63e151675ca6898 v4.1 drivers/gpu/drm/radeon/".

This helped, at least to compile and boot one kernel.
I told git bisect it was a good revision: # good: [c65b99f046843d2455aa231747b5a07a999a9f3d] Linux 4.1-rc6
git bisect good c65b99f046843d2455aa231747b5a07a999a9f3d
and proceeded to compile the kernel with the next commit that git bisect jumped to, commit d55a43a3e9258c01a6cac2f3081b3ceaa8e58020. That kernel compiled, though the folder the "make modules_install' command built was called linux-4.1.0-rc4 instead of -rc6 like the previous. 

And boom...freezing on 'loading initial ramdisk' yet again. There were about 21 commits left to check, so I played the odds that that one wasn't the bad commit and ran 'git bisect skip' to skip it and force bisect to move to another commit. Compiled the kernel again, and that one also failed to boot at "loading initial ramdisk." In an attempt to resolve, I've ran 'make localyesconfig' to compile in support for all my devices into the kernel, so technicially no initial ramdisk should even be needed. I've swapped ina default linux-4.3 default ubuntu kernel config file, and used 'zcat /proc/config > .config" to copy the running kernel's configs from both the 4.1.12 and 4.3.0 stock Manjaro kernels. I've added "systemd' to my HOOKS in mkinitcpio.conf in the event the initial ramdisk needed systemd support. Still nothing but a freeze at boot, on 'loading initial ramdisk.' Should I keep skipping over commits and compiling kernels until I can compile one that actually boots, or is there something I'm overlooking here that's needed that the stock Manjaro kernel configs don't provide and neither does the Ubuntu one. I'm using the instructions from https://wiki.archlinux.org/index.php/Kernels/Compilation/Traditional, and until hitting that one commit and then running into the same problem later when restricting the bisect to drivers/gpu/drm/radeon, it worked and the kernels I compiled booted up correctly.

**Comment by philmmanjaro** [comment]
@overclockedoncoffee: Slow down. You're on the right path. However I'd recommend to do a project out of it. Like I did [before](https://github.com/philmmanjaro/linux41). With **git-bisect** you might find it. The tip to just focus on radeon changes is good. However it won't matter. 

Finding the issue takes a while. If you don't skip you will find an answer. Check the log and the timestamps of my [PKGBUILD](https://github.com/philmmanjaro/linux41/commits/master/PKGBUILD) and how long it took on my end. Check also my [git-bisect.txt](https://github.com/philmmanjaro/linux41/blob/master/git-bisect.txt). It includes all commands I did with the bisect.

I recommend to use tarballs and a **PKGBUILD** with help of **manjaro-tools (buildpkg)** or **makepkg**. Sometimes the [config](https://github.com/philmmanjaro/linux41/commits/master/config) changes. So keep track on it. Also it is recommended to uncomment my patches.

Hope this helps you a little. If needed I can make a tutorial out of it.

**Comment by overclockedoncoffee** [comment]
@philmmanjaro: Start my own github project? Don't use the upstream git tree, but tarballs instead? Where do I grab those? Kernel.org has the current updated kernels from each series, but I don't think they have the rc kernels for older versions do they? And by using tarballs instead of a git tree, won't that strip away any records of commits for bisect to read from, or is all the commit history also part of each upstream tarball? Also, my config file wasn't changing, unless I manually deleted it and copied over a new one via zcat > /proc/config.gz > .config to switch to the one from either 4.1 or 4.3 when the other didn't work....I'm slightly confused...

Actually, yes, I think a tutorial would be very helpful--I won't be insulted if you write it as if I'm a complete newbie, because better too much detail than the opposite. I've used PKGBUILDS before, and edited a lin or two, but never wrote one myself. Failing that, a sample config file you used to compile any recent kernel successfully, and which I could copy/paste in my source directory as my new config and compile again, would be helpful. It's obviously something broken in the release around commit d55a43a3e9258c01a6cac2f3081b3ceaa8e58020 or something in my tree, but without a known workable config it's hard to say which it is...thanks again for the assistance!

**Comment by overclockedoncoffee** [comment]
@philmmanjaro: Start my own github project? Don't use the upstream git tree, but tarballs instead? Where do I grab those? Kernel.org has the current updated kernels from each series, but I don't think they have the rc kernels for older versions do they? And by using tarballs instead of a git tree, won't that strip away any records of commits for bisect to read from, or is all the commit history also part of each upstream tarball? Also, my config file wasn't changing, unless I manually deleted it and copied over a new one via zcat > /proc/config.gz > .config to switch to the one from either 4.1 or 4.3 when the other didn't work....I'm slightly confused...

Actually, yes, I think a tutorial would be very helpful--I won't be insulted if you write it as if I'm a complete newbie, because better too much detail than the opposite. I've used PKGBUILDS before, and edited a lin or two, but never wrote one myself. Failing that, a sample config file you used to compile any recent kernel successfully, and which I could copy/paste in my source directory as my new config and compile again, would be helpful. It's obviously something broken in the release around commit d55a43a3e9258c01a6cac2f3081b3ceaa8e58020 or something in my tree, but without a known workable config it's hard to say which it is...thanks again for the assistance!

**Comment by overclockedoncoffee** [comment]
@philmmanjaro: Start my own github project? Don't use the upstream git tree, but tarballs instead? Where do I grab those? Kernel.org has the current updated kernels from each series, but I don't think they have the rc kernels for older versions do they? And by using tarballs instead of a git tree, won't that strip away any records of commits for bisect to read from, or is all the commit history also part of each upstream tarball? Also, my config file wasn't changing, unless I manually deleted it and copied over a new one via zcat > /proc/config.gz > .config to switch to the one from either 4.1 or 4.3 when the other didn't work....I'm slightly confused...

Actually, yes, I think a tutorial would be very helpful--I won't be insulted if you write it as if I'm a complete newbie, because better too much detail than the opposite. I've used PKGBUILDS before, and edited a lin or two, but never wrote one myself. Failing that, a sample config file you used to compile any recent kernel successfully, and which I could copy/paste in my source directory as my new config and compile again, would be helpful. It's obviously something broken in the release around commit d55a43a3e9258c01a6cac2f3081b3ceaa8e58020 or something in my tree, but without a known workable config it's hard to say which it is...thanks again for the assistance!

**Comment by philmmanjaro** [comment]
@overclockedoncoffee: Using tarballs is easy. I use the **torvalds github repo** for that. See the first commit to my [PKGBUILD](https://github.com/philmmanjaro/linux41/commit/013420365894bc099214cc797f8cecf92e904325) using a **git-bisect** git-commit. So here we go:

Start the normal git-bisect as I did within my [project file](https://github.com/philmmanjaro/linux41/blob/master/git-bisect.txt). There you see how I used **git-bisect** to find my issue.

Second part is to clone the **linuxXY** PKGBUILD and all needed files from my git-repo: `git clone https://github.com/manjaro/packages-core.git`. Simply change it as similar as within my [PKGBUILD](https://github.com/philmmanjaro/linux41/commit/013420365894bc099214cc797f8cecf92e904325). I recommend to disable all additional patches so it won't fail cos of them.

After you have the first **git-commit** from **git-bisect** you have to check, simply edit the **_bisect** value and give it a name in **_rc**. That you find out with the given first git-commit git-bisect gives you:

```
git bisect start
git bisect good v4.1
git bisect bad v4.2
```

After testing the first compile install that kernel and decide if it works for you or not. Then go on. You might get an information like **Bisecting: 5576 revisions left to test after this (roughly 13 steps)**. Depending on your CPU power it will take a while. So first prepare your **PKGBUILD**, then do the first compile, test that kernel, go again with git-bisect by repeating the steps until you find your defined bad first commit. And don't skip. In the end you want to read some similar like **0d55ba46bfbee64fd2b492b87bfe2ec172e7b056 is the first bad commit**. With that info you can push the developer for a fix.

**Comment by philmmanjaro** [comment]
Additional info: **Linux 4.1-rc0-b1-6c373ca893** means that the issue is pre-rc1 and b1 was my first build. Lastly I noted down the git-commit I used. Just post if my "tutorial" is not fully understandable yet.

**Comment by philmmanjaro** [comment]
Also you have to define if the issue was introduced within **v4.2** or not. You need to know at least one known to you kernel which is not working for you.

**Comment by overclockedoncoffee** [comment]
But I've established and good and bad kernel back when I initially noticed the bug. At the time, I was running 4.1.11 (which worked) and I'd recently installed 4.2.3.0 (it did not--it booted but no accel.) So there are my starting points, no? Actually, I've narrowed it down further than that. I've already been bisecting for weeks, and I've isolated it down to around 21 commits, with the last commit that resulted in a kernel that even booted being c65b99f046843d2455aa231747b5a07a999a9f3d. Do I need to start all over again? Or are you saying to keep two distinct source trees? The one I'm bisecting now, which contains the complete development history of the linux kernel going as far back as Linus's git tree goes, and another where I do my pkgbuilds? Build and install from the pkgbuild tree, and then use the git bisect commands after changing directory to my copy of linus's tree? If I do that, how do I modify the pkbuild to fetch the history only up to a certain commit?

**Comment by philmmanjaro** [comment]
@overclockedoncoffee: so you claim **c65b99f Linux 4.1-rc6** broken or working? This is to far down. You say that **4.1.11** works for you. So does **4.1** also works for you? What was the first not working kernel? Did you test **4.2-rc1** already? Most times issues will get introduced with the first RC of a new kernel.

Bisecting will always take the same amount of compiles. It really doesn't matter which range you choose. However, the bigger the range it might take a little longer to do so as the middle is more in both ways. It is recommend to just use versions given by the linus-torvalds tree. Gregs point-releases are fine but not recommended. How long does one compile take for you?

So define the lowest not working kernel and the highest kernel which worked. So if **v4.1** works and **v4.2** not those are your starting points. If v4.2-rc1 doesn't work for you you choose that one as your top. [v4.2-rc1 PKGBUILD](https://github.com/manjaro/packages-core/archive/be65b55aa423b1405f0783371e93326fcae7dfa7.zip) is available from the git-repository. So compare it with my [first commit](https://github.com/philmmanjaro/linux41/commit/013420365894bc099214cc797f8cecf92e904325) I did for the bisecting on my issue and change it accordingly.

**Comment by overclockedoncoffee** [comment]
@philmmanjaro: Kernel commit c65b99f Linux 4.1-rc6 compiles, boots, and 3-d accel works under it.

As fas as 4.1-rc6 being too early, I would agree in theory since kernel 4.1.11 and every other kernel in the 4.1.1x series I've installed from the Manjaro repositories works, but that's the kernel thhat my compile built based on the command/s I was simply copying and pasting from Christian Konig's instructional comments on my freedesktop.org bug report. I did so because I'm guessing he's been through a lot more git bisects than I have and closed a lot more bug reports. Can you re-read the thread on https://bugs.freedesktop.org/show_bug.cgi?id=92858 and see if there's a command I could've misread and as a result compiled a different kernel than I should've?

I actually attempted to compile the 4.2-rc1 kernel using the PKGBUILD from your git-repository, but the compile failed on the following:

scripts/Makefile.build:258: recipe for target 'fs/aufs/i_op.o' failed
make[2]: *** [fs/aufs/i_op.o] Error 1
scripts/Makefile.build:403: recipe for target 'fs/aufs' failed
make[1]: *** [fs/aufs] Error 2
Makefile:943: recipe for target 'fs' failed
make: *** [fs] Error 2
==> ERROR: A failure occurred in build().

Is there no archive of ready-built binary packages of each kernel rc version I could install to locate a more accurate starting point? Kernel compiles take around an hour I'd say, on my computer, if I use make -j[processor cores.]

**Comment by philmmanjaro** [comment]
Ah right, please disable the Aufs patches and the aufs.config. Check with [my commit](https://github.com/philmmanjaro/linux41/commit/013420365894bc099214cc797f8cecf92e904325) to see what I mean by that. You have to dash (#) them.

**Comment by philmmanjaro** [comment]
@overclockedoncoffee: Basically he told you the same as I told you here. I simply used the old style:
```
git bisect start
git bisect good v4.1
git bisect bad v4.2
```

He used the one liner:
```
git bisect start v4.2 v4.1
```

Both will lead to the same result:
**"Bisecting: 7353 revisions left to test after this (roughly 13 steps)
[c11d716218910c3aa2bac1bb641e6086ad649555] Merge tag 'armsoc-cleanup' of git://git.kernel.org/pub/scm/linux/kernel/git/arm/arm-soc"**

What I only did was to use the commit hash **c11d716218910c3aa2bac1bb641e6086ad649555** in your case and downloaded that tarball in my PKGBUILD as I wanted to have a clean source and like to use packages for this.

Then you go either **git bisect bad** or **git bisect good**. You don't need to add the commit hash after it. Git already knows that. Simply get the new hash you should check and edit your PKGBUILD. Check therefore my [changelog](https://github.com/philmmanjaro/linux41/commits/master/PKGBUILD).

If you get stuck, either skip or try it once more. Always remove extra patches from the PKGBUILD. Nothing else was told here or by Christian König.

The cmd `git bisect start c5fd936e992dd2829167d2adc63e151675ca6898 v4.1 drivers/gpu/drm/radeon/` just starts a new git-bisect with the focus on changes of **drm-radeon**. This was also your last bisect you claimed to be bad. So it doesn't matter if you stop your bisect. You can always begin new with the latest commit hash you have declared either way.

**Comment by overclockedoncoffee** [comment]
@philmmanjaro: I built and installed kernel 4.2-rc1 and no 3-d accel. So, I've at least identified a definitive starting point. I've started the bisect once again, with:

git bisect start
git bisect good v4.1
git bisect bad v4.2-rc1

Bisecting: 6261 revisions left to test after this (roughly 13 steps)

The initial commit is '[4570a37169d4b44d316f40b2ccc681dc93fedc7b] Merge tag 'sound-4.2-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.' So now I simply paste '4570a37169d4b44d316f40b2ccc681dc93fedc7b into the '+bisect=' field in the PKGBUILD, and build again? In that case, what would go into the '-bisect' field, since git bisect didn't output the commit immediately before that one?

Regarding skipping or trying once more, I haven't actually had any problems building the kernels--they all compiled successfully and installed, even usuing the manual method of install. Once I got to a certain kernel commit, though, the kernels I built froze at boot, on "loading initial ramdisk' If I run into one of these again, and compiling over doesn't fix, do you advise skipping it and proceeding to the next kernel commit?

**Comment by philmmanjaro** [comment]
**4570a37169d4b44d316f40b2ccc681dc93fedc7b** is the commit hash you should test, so yes. It is your first **bisect=**. Compare this: [PKGBUILD Build1](https://github.com/philmmanjaro/linux41/commit/013420365894bc099214cc797f8cecf92e904325) with the **git-bisect.txt** at the end. Also notice that I removed all extra patches and the **config** file changed. You can add **SKIP** to the checksums for the **config** file and use **makepkg** to compile your **PKGBUILD**. When the questions for the config appear simply press **Enter** and start compiling. After compiling the kernel, install it, reboot the system and decide if it is either bad or good. Then you go back to your git-bisect to get the next git hash you should check. This would be then [PKGBUILD Build2](https://github.com/philmmanjaro/linux41/commit/3b836896ee3e77fd33160cd96501f9a40c352858). Be sure that your PKGBUILD look similar to [this one](https://github.com/philmmanjaro/linux41/blob/master/PKGBUILD) before starting your first build. Notice the **linux-${_bisect}** changes and the patch disables. If you still have some questions, just shoot ;)

**Comment by overclockedoncoffee** [comment]
Closing the bug as unable to duplicate.

**Comment by overclockedoncoffee** [comment]
I thus far have still been unable to locate the commit that broke acceleration due to unbootable kernels. I'll buy a replacement video card or switch to the built-in.
