### ISSUE TITLE
manjaro-keyring version

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-core#21]
Since I keep seeing this during upgrade
```
warning: manjaro-keyring: local (20151108-1) is newer than core (20150809-1)
```
I went to check what's going on with this pkg but I cannot see any commits since August and no hint of a version 20151108 anywhere.
In any case, do I downgrade?

**Comment by philmmanjaro** [comment]
This was a **cinnamon** temp fix and not needed. Please downgrade.

**Comment by oberon2007** [comment]
Ok. Thanks.
