### ISSUE TITLE
default umask value and group definitions too permissive

### ISSUE THREAD

**Issue by Boruch-Baum** [manjaro/packages-core#26]
For anyone planning to use manjaro as a multi-user system, the access rights are way too permissive. Since all users share membership in the same default primary group "users", the current default umask value allows anyone to peek into anyone else's data.

My expectation was that personal data would be private by default. At this point, I've changed the situation on my box, but y'all may want to check, for instance, your .ssh and gnupg folder permissions.

Also, my expectation (coming from debian, as I do) was that each user would be assigned a 'personal group', instead of being lumped together with every other user by default.

**Comment by philmmanjaro** [comment]
This is already addressed and will be handled with **16.03 Daniella** release by default.

**Comment by philmmanjaro** [comment]
This is applied to our 16.06-preX builds. Please test and report back.
