### ISSUE TITLE
[linux44] Fix sdhci regression, Fix asus_laptop module causes a kernel panic

### ISSUE THREAD

**Issue by FadeMind** [manjaro/packages-core#27]
Please apply this patches for linux44 series due major regressions:
 - Revert patch [mmc: sdhci: enable tuning for DDR50](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=9faac7b95ea4f9e83b7a914084cc81ef1632fd91) due 
[FS#47778 4.4.x sdhci regression](https://bugs.archlinux.org/task/47778)<br/>
`patch -Rp1 -i "${srcdir}/0001-rev_mmc-sdhci-enable tuning_for_DDR50.patch"`<br/>
[**Patch code**](https://raw.githubusercontent.com/FadeMind/archpkgbuilds/master/AUR/mainline/linux-mainline/0001-rev_mmc-sdhci-enable%20tuning_for_DDR50.patch)
 - Applying patch [base/platform: fix binding for drivers without probe callback for fix](https://patchwork.ozlabs.org/patch/552082/) due 
[FS#47805 4.4.x asus_laptop module causes a kernel panic](https://bugs.archlinux.org/task/47805)<br/>
[**Patch code**](https://raw.githubusercontent.com/FadeMind/archpkgbuilds/master/AUR/mainline/linux-mainline/0001-base-platform-fix-binding-for-drivers-without-probe-callback.patch)
<br/>
Reference: https://github.com/FadeMind/archpkgbuilds/commit/f85f374eb1eb3ecafa808487d3db3cecfef19d5f

@philmmanjaro

I applied them for linux-mainline (4.4) - build fine, kernel working as expexted.

**Comment by philmmanjaro** [comment]
The first issue seems to be also in **4.3** since rc6. However I see no comment upstream to revert this at all. The second issue makes sense. I might include that one in the next kernel series.

**Comment by FadeMind** [comment]
@philmmanjaro https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=b795c4ea0ded112734255d87864bbda1e844cd64
