### ISSUE TITLE
Update to new kernels

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#30]
New kernels are out:

* 3.10.101
* 3.12.57
* 3.14.65
* [3.19.8.17](https://patchwork.kernel.org/patch/8633801/)
* 4.1.20
* [4.2.8.6](https://patchwork.kernel.org/patch/8633791/)
* 4.4.6

**Comment by philmmanjaro** [comment]
Check if there is a new aufs release. To update the kernels is optional but recommended

**Comment by Kirek** [comment]
Will do. **4.4.6** is done

**Comment by Kirek** [comment]
From where do you get the "aufs4.4-20160301.patch.bz2" patches?

**Comment by Kirek** [comment]
Forget that, found the script.

**Comment by Kirek** [comment]
**4.2.8.6** done

**Comment by Kirek** [comment]
**4.1.20** done

**Comment by philmmanjaro** [comment]
Seems I forgot to upload that. Good you found it

**Comment by philmmanjaro** [comment]
Also check if due ABI changes the extra modules are in need of a rebuild

**Comment by Kirek** [comment]
I'm rebuilding all of them just to be safe.
**3.19.8.17** done

**Comment by philmmanjaro** [comment]
To check that I've a [script]https://github.com/manjaro/packages-core/blob/master/kernel-modules-sum.sh)

**Comment by Kirek** [comment]
**3.14.65** done
Seems that zfs has been updated too https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.6

**Comment by Kirek** [comment]
**3.10.101** and **3.12.57** done too.

**Comment by philmmanjaro** [comment]
Yes sometimes that happens. Either update or leave the old version.
