### ISSUE TITLE
Drop linux43

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#31]
We should think about when it will be best to drop this depreciated kernel series. There is no ESS kernel planned for it

**Comment by Kirek** [comment]
Anytime, I don't think is very used.
Maybe we should drop 3.10 too https://github.com/systemd/systemd/issues/2800

**Comment by philmmanjaro** [comment]
**systemd-coredump** may not work with **3.10 series**, but doesn't prevent users to use **systemd** with that kernel series. Simply a function is not working ...

**Comment by philmmanjaro** [comment]
Followed kernels will loose their extended stable support:

**End of 2015**

* 3.10  (don't know how long Greg will support it still)

**April 2016**

* 3.16
* 3.13 

**July 2016**

* 3.19 

**August 2016**

* 4.2
* 3.14

**Comment by Kirek** [comment]
Should we drop 4.13 this stable update cycle? It's already almost two months old.

**Comment by korrode** [comment]
+1 for dropping 4.3

**Comment by philmmanjaro** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160404/006641.html
