### ISSUE TITLE
Move bootloader auto-updating to a better place

### ISSUE THREAD

**Issue by mirh** [manjaro/packages-core#32]
As noted down in the [forums](https://forum.manjaro.org/index.php?topic=32481.0) I'm not sure the kernel package itself is the best place to place bootloader updating. 
For example MSM is already better, and there wouldn't be any problem should you decide to add complexity in code to support more bootloaders. 

Relates to manjaro/manjaro-settings-manager#52

**Comment by philmmanjaro** [comment]
@mirh: by default we use **grub** as bootloader. With each kernel update we also update our **grub.cfg**. To check if **grub** is installed can be acchived by `sudo dd bs=512 count=1 if=/dev/sda 2>/dev/null | strings|grep GRUB`. However this might vary for each installation. The place for updating **grub.cfg** is right. The way for detecting if **grub** is used however might be wrong ...

**Comment by udeved** [comment]
Would also be a possible hook application.
Instead of triggering update-grub after each kernel package, we can also trigger it post transaction once if any kernel is updated or installed,
https://github.com/manjaro/release-plan/issues/39

**Comment by mirh** [comment]
As long as you officially support only a single bootloader I guess it doesn't make any difference after all. 
I managed to still install systemd-boot with thus, but I [see](https://github.com/manjaro/thus/issues/51) that's being deprecated. 
But I thought that everything it had was going to be moved to calamares eventually. So is systemd-boot being deprecated too?

**Comment by philmmanjaro** [comment]
The missing parts **calamares** is still missing are in development currently. **v2.3** should support disk encryption. **systemd-boot** is supported by **calamares**. However **Manjaro** goes by [default for **grub**](https://github.com/calamares/calamares/blob/master/src/modules/bootloader/bootloader.conf).

**Comment by mirh** [comment]
Cool, thanks for the info. 
So.. do you think there's still room in the future for that, or had I better to close this issue?

**Comment by philmmanjaro** [comment]
You can keep this report open as an reminder. We are always working on improving the user experince within Manjaro. Maybe the hook support might fix it properly ...

**Comment by philmmanjaro** [comment]
This will fix the issue: https://github.com/manjaro/packages-core/commit/cb983c1e7191a55570a2b3de7b51fc95c653ff01, https://github.com/manjaro/packages-core/commit/8f1741b86323d26715e40d2792ce92164f1f46d0
