### ISSUE TITLE
[linuxXX] Packager was not set

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-core#34]
The packager was not set in the latest kernel builds.
The kernel packages show "unknown" packager.

**Comment by philmmanjaro** [comment]
Which kernel you claim about? Some were done by @Kirek.

**Comment by philmmanjaro** [comment]
All kernels around 23th of March were built by @Kirek without proper **makepkg.conf** settings. That is why no packager was set.

**Comment by Kirek** [comment]
Didn't notice... my makepkg.conf was fine, but apparently bulding in a clean chroot doesn't like accents. 
Using Ramon Buldo instead of Ramon Buldó works.

**Comment by Kirek** [comment]
Apparently this happens because it forces LANG=C.

**Comment by Kirek** [comment]
http://blog.gmane.org/gmane.linux.arch.projects/month=20160201
