### ISSUE TITLE
Sound module for I2S broadwell audio interface is not provided with kernel >=4.5

### ISSUE THREAD

**Issue by cheesewick** [manjaro/packages-core#35]
For I2S broadwell audio interface (available in some laptops i.e. dell xps)  `snd-soc-sst-broadwell` sound module is needed.

Unfortunately it isn't compiled by default in kernel >=4.5 (4.4 works fine) because of https://github.com/torvalds/linux/commit/a92ea59b74e231cc0a969afa8d71fa314d5860f2.

To fix it, the following changes in kernel compile config is needed:
`CONFIG_DW_DMAC=y`
`CONFIG_SND_SOC_INTEL_HASWELL_MACH=m`
`CONFIG_SND_SOC_INTEL_BROADWELL_MACH=m`

For reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1317214
https://bugzilla.redhat.com/show_bug.cgi?id=1308792
https://bugs.archlinux.org/task/48936

**Comment by philmmanjaro** [comment]
Seems now CONFIG_DW_DMAC_CORE=y is needed in the config.  If not, then the modules aren't available.  This was changed with:

```
commit a92ea59b74e231cc0a969afa8d71fa314d5860f2
Author: Jie Yang <yang.jie@intel.com>
Date:   Tue Nov 24 22:01:21 2015 +0800

    ASoC: Intel: sst: only select sst-firmware when DW DMAC is built-in
```
Which sounds all fine, except it's pretty terrible from a distribution standpoint.  Now we're left with the choice of everyone running a kernel having to carry DW_DMAC_CORE in-memory regardless of whether or not their machine use it (which most don't), or leaving the modules missing for the few machines that actually need it.

**Comment by philmmanjaro** [comment]
I'm more for reverting the commit for now and wait until [alsa has a proper fix](http://mailman.alsa-project.org/pipermail/alsa-devel/2016-March/105574.html) for it.

**Comment by cheesewick** [comment]
Yes, reverting https://github.com/torvalds/linux/commit/a92ea59b74e231cc0a969afa8d71fa314d5860f2 should fix any issues for now.

**Comment by cheesewick** [comment]
It looks that arch decided to keep commit and change config similarly as I described in first comment.
https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=2a4c58b5c252a9666fff294b479efc29de8f4acc

**Comment by philmmanjaro** [comment]
I'll go with the revert. Can be tested with the soon to be released **4.6-rc5**.

**Comment by philmmanjaro** [comment]
[Feedback](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160425/006898.html) please :smile:

**Comment by cheesewick** [comment]
It works for me. Thanks for support.

**Comment by philmmanjaro** [comment]
Great. Then I'll do the same for **v4.5** series later on, when a new point-release will come out ...
