### ISSUE TITLE
[linux319] missing gcc 6 header file

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#41]
Seems with using gcc all new kinds of issues occur ...

**3.19.8.21**
```
In file included from include/linux/compiler.h:54:0,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from include/linux/page-flags.h:8,
                 from kernel/bounds.c:9:
include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
compilation terminated.
```

**Comment by FadeMind** [comment]
https://github.com/torvalds/linux/commit/3f3f8d2f48acfd8ed3b8e6b7377935da57b27b16

**Comment by philmmanjaro** [comment]
It is more or less this:

https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?h=linux-3.14.y&id=3711edaf01a01818f2aed9f21efe29b9818134b9
https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?h=linux-3.14.y&id=615829a03dc729e78372d40d95ba40e2ad51783b

**Comment by FadeMind** [comment]
So, header need new rule for gcc6 then.

https://github.com/torvalds/linux/blob/cb984d101b30eb7478d32df56a0023e4603cba7f/include/linux/compiler-gcc.h#L225

**Comment by philmmanjaro** [comment]
Seems I've to create the patch for **3.19 series** ...
