### ISSUE TITLE
linux47 initramfs isn't removed on uninstall

### ISSUE THREAD

**Issue by mirh** [manjaro/packages-core#44]

**Comment by philmmanjaro** [comment]
@mirh: you know that this is a really early build of the package. Which file does not get removed exactly?

**Comment by philmmanjaro** [comment]
This is are the values from the install file:

```
RELEASE=4.7rc1-1
KERNEL_VERSION=4.7.0-1-MANJARO
KERNEL_BASE=4.7-rc1
BASEVER=47
ARCH=x86_64
```

**kernel-base** should be **4.7** to get the **initramfs** file removed. This will be fixed with **rc2** as it was wrongly configured with this package release.

**Comment by philmmanjaro** [comment]
See also https://github.com/manjaro/packages-core/commit/1f8c09624cf0c839c497ba9361eb4bdcce3ccb4f

**Comment by mirh** [comment]
Cool, thanks.
