### ISSUE TITLE
linux46: PKGBUILD sha256sums not updated after added patches

### ISSUE THREAD

**Issue by poorswing** [manjaro/packages-core#46]
sha256sums in PKGBUILD of linux46 repo should be updated after https://github.com/manjaro/packages-core/commit/0e8314eb790c0803cddb3e1f289ab8deca1f8488 commit. Currently sha256sums of added patches are missing.

**Comment by philmmanjaro** [comment]
git doesn't match always what I've locally on my development machine. I'm currently building **v4.6.2** anyway, which provides different shasums.
