### ISSUE TITLE
remove AMD GCN1.1 cards from MHWD-AMDGPU support

### ISSUE THREAD

**Issue by SanKro** [manjaro/packages-core#47]
right now its not possible to install manjaro 16.06 to any computer with a GCN1.1 Card (Hawaii, Bonaire, Kaveri blah blah)
its because of our change to support those cards with AMDGPU.

now the installer -> mhwg defaults to AMDGPU and crashes because the experimental support dont work.

now my wich is to remove the IDs for all GCN 1.1 cards/APUs from mhwd-amdgpu prober. so that all thos cards will use "radeon"(xf86-video-ati) again and the amdgpu kernel module will not be loaded.

is there a list with those PCIIDs somewhere or do we have to collect them by ourself?

**Comment by philmmanjaro** [comment]
We auto generate the list given by the **amdgpu** driver. PKGBUILD and script can been found here:
https://github.com/manjaro/packages-core/blob/master/mhwd-amdgpu

**Comment by SanKro** [comment]
is there a way to change this to a lower layer? its not just AMDGPU, but also RADEON (xf86-video-ati)
for example: in KDE Driver manager in manjaro. with an R9 380 (Tonga, GCN 1.2) you can also choose "video-ati". if you set this X wont start anymore, because radeon dont supports this card. AMDGPU is the only one with working support.

the best way would be to ask the firmware directory because its splittet up the correct way
/lib/firmware/radeon/
for all cards/chips who really works with radeon (kernel module and xorg driver)

/lib/firmware/amdgpu/
for all the cards/chips with working amdgpu support.

i mean its not entirely wrong that there is "amdgpu" support for GCN 1.1 cards, because there is experimental support. but mhwd should not show the option or loads it by default.

right now the realworld situation is:
GCN1.0 -> radeon only
GNC1.1 -> radeon full support, amdgpu experimental
GCN1.2 -> amdgpu only

but for manjaro
GCN1.0 -> radeon only [works}
GNC1.1 -> amdgpu first [breaks X], radeon as option [would work]
GCN1.2 -> amdgpu first [works], radeon as option [would break X]

**Comment by philmmanjaro** [comment]
This is the list for [supported cards](https://cgit.freedesktop.org/xorg/driver/xf86-video-amdgpu/tree/src/pcidb/ati_pciids.csv) by **amdgpu**. And this the list of [supported cards](https://cgit.freedesktop.org/xorg/driver/xf86-video-ati/tree/src/pcidb/ati_pciids.csv) by **ati** driver. Now I need a list of these drivers we should remove to be detected for **amdgpu** by **mhwd**.

**Comment by philmmanjaro** [comment]
Use ID file for **xf86-video-ati** (https://github.com/manjaro/mhwd-db/commit/c9b80ac8a523ce1c9e2ebeb2562dcea9f987cfc4, https://github.com/manjaro/packages-core/commit/6ef20e1b21056a1b2ca52e76d2889fbe0d496cf1)

**Comment by philmmanjaro** [comment]
**GCN 1.1**

Discrete GPUs (Sea Islands family):

* Bonaire
* Hawaii

Integrated into APUs:

* Temash
* Kabini
* Liverpool
* Durango
* Kaveri
* Godavari
* Mullins
* Beema
* Carrizo-L

**GCN 1.2**

Discrete GPUs:

* Tonga (Volcanic Islands family), comes with UVD 5.0
* Fiji (Pirate Islands family), comes with UVD 6.0 and High Bandwidth Memory (HBM 1)

Integrated into APUs:

* Carrizo, comes with UVD 6.0
* Bristol Ridge

**GCN 1.3**

Discrete GPUs:

* Polaris 10
        Renamed from Ellesmere
        2 discrete GPUs planned for release
* Polaris 11
        Renamed from Baffin
        6 discrete GPUs planned for release

Integrated into APUs:

* Future Zen Powered APUs (launching in H1 2017)

**Comment by philmmanjaro** [comment]
So in other words you want me to remove followed cards to be auto dected, even we have enabled **experimental support for GCN 1.1** after another user request?

```
"#pciid","define","family","name"
"0x6640","BONAIRE_6640","BONAIRE","BONAIRE"
"0x6641","BONAIRE_6641","BONAIRE","BONAIRE"
"0x6646","BONAIRE_6646","BONAIRE","BONAIRE"
"0x6647","BONAIRE_6647","BONAIRE","BONAIRE"
"0x6649","BONAIRE_6649","BONAIRE","BONAIRE"
"0x6650","BONAIRE_6650","BONAIRE","BONAIRE"
"0x6651","BONAIRE_6651","BONAIRE","BONAIRE"
"0x6658","BONAIRE_6658","BONAIRE","BONAIRE"
"0x665C","BONAIRE_665C","BONAIRE","BONAIRE"
"0x665D","BONAIRE_665D","BONAIRE","BONAIRE"
"0x665F","BONAIRE_665F","BONAIRE","BONAIRE"
"0x9830","KABINI_9830","KABINI","KABINI"
"0x9831","KABINI_9831","KABINI","KABINI"
"0x9832","KABINI_9832","KABINI","KABINI"
"0x9833","KABINI_9833","KABINI","KABINI"
"0x9834","KABINI_9834","KABINI","KABINI"
"0x9835","KABINI_9835","KABINI","KABINI"
"0x9836","KABINI_9836","KABINI","KABINI"
"0x9837","KABINI_9837","KABINI","KABINI"
"0x9838","KABINI_9838","KABINI","KABINI"
"0x9839","KABINI_9839","KABINI","KABINI"
"0x983A","KABINI_983A","KABINI","KABINI"
"0x983B","KABINI_983B","KABINI","KABINI"
"0x983C","KABINI_983C","KABINI","KABINI"
"0x983D","KABINI_983D","KABINI","KABINI"
"0x983E","KABINI_983E","KABINI","KABINI"
"0x983F","KABINI_983F","KABINI","KABINI"
"0x1304","KAVERI_1304","KAVERI","KAVERI"
"0x1305","KAVERI_1305","KAVERI","KAVERI"
"0x1306","KAVERI_1306","KAVERI","KAVERI"
"0x1307","KAVERI_1307","KAVERI","KAVERI"
"0x1309","KAVERI_1309","KAVERI","KAVERI"
"0x130A","KAVERI_130A","KAVERI","KAVERI"
"0x130B","KAVERI_130B","KAVERI","KAVERI"
"0x130C","KAVERI_130C","KAVERI","KAVERI"
"0x130D","KAVERI_130D","KAVERI","KAVERI"
"0x130E","KAVERI_130E","KAVERI","KAVERI"
"0x130F","KAVERI_130F","KAVERI","KAVERI"
"0x1310","KAVERI_1310","KAVERI","KAVERI"
"0x1311","KAVERI_1311","KAVERI","KAVERI"
"0x1312","KAVERI_1312","KAVERI","KAVERI"
"0x1313","KAVERI_1313","KAVERI","KAVERI"
"0x1315","KAVERI_1315","KAVERI","KAVERI"
"0x1316","KAVERI_1316","KAVERI","KAVERI"
"0x1317","KAVERI_1317","KAVERI","KAVERI"
"0x131B","KAVERI_131B","KAVERI","KAVERI"
"0x131C","KAVERI_131C","KAVERI","KAVERI"
"0x131D","KAVERI_131D","KAVERI","KAVERI"
"0x67A0","HAWAII_67A0","HAWAII","HAWAII"
"0x67A1","HAWAII_67A1","HAWAII","HAWAII"
"0x67A2","HAWAII_67A2","HAWAII","HAWAII"
"0x67A8","HAWAII_67A8","HAWAII","HAWAII"
"0x67A9","HAWAII_67A9","HAWAII","HAWAII"
"0x67AA","HAWAII_67AA","HAWAII","HAWAII"
"0x67B0","HAWAII_67B0","HAWAII","HAWAII"
"0x67B1","HAWAII_67B1","HAWAII","HAWAII"
"0x67B8","HAWAII_67B8","HAWAII","HAWAII"
"0x67B9","HAWAII_67B9","HAWAII","HAWAII"
"0x67BA","HAWAII_67BA","HAWAII","HAWAII"
"0x67BE","HAWAII_67BE","HAWAII","HAWAII"
```

And only keep **GCN 1.2** GPUs in it? 

```
"0x6900","TOPAZ_6900","TOPAZ","TOPAZ"
"0x6901","TOPAZ_6901","TOPAZ","TOPAZ"
"0x6902","TOPAZ_6902","TOPAZ","TOPAZ"
"0x6903","TOPAZ_6903","TOPAZ","TOPAZ"
"0x6907","TOPAZ_6907","TOPAZ","TOPAZ"
"0x6920","TONGA_6920","TONGA","TONGA"
"0x6921","TONGA_6921","TONGA","TONGA"
"0x6928","TONGA_6928","TONGA","TONGA"
"0x6929","TONGA_6929","TONGA","TONGA"
"0x692B","TONGA_692B","TONGA","TONGA"
"0x692F","TONGA_692F","TONGA","TONGA"
"0x6930","TONGA_6930","TONGA","TONGA"
"0x6938","TONGA_6938","TONGA","TONGA"
"0x6939","TONGA_6939","TONGA","TONGA"
"0x9870","CARRIZO_9870","CARRIZO","CARRIZO"
"0x9874","CARRIZO_9874","CARRIZO","CARRIZO"
"0x9875","CARRIZO_9875","CARRIZO","CARRIZO"
"0x9876","CARRIZO_9876","CARRIZO","CARRIZO"
"0x9877","CARRIZO_9877","CARRIZO","CARRIZO"
"0x7300","FIJI_7300","FIJI","FIJI"
"0x98E4","STONEY_98E4","STONEY","STONEY"
"0x67E0","POLARIS11_67E0","POLARIS11","POLARIS11"
"0x67E3","POLARIS11_67E3","POLARIS11","POLARIS11"
"0x67E8","POLARIS11_67E8","POLARIS11","POLARIS11"
"0x67EB","POLARIS11_67EB","POLARIS11","POLARIS11"
"0x67EF","POLARIS11_67EF","POLARIS11","POLARIS11"
"0x67FF","POLARIS11_67FF","POLARIS11","POLARIS11"
"0x67E1","POLARIS11_67E1","POLARIS11","POLARIS11"
"0x67E7","POLARIS11_67E7","POLARIS11","POLARIS11"
"0x67E9","POLARIS11_67E9","POLARIS11","POLARIS11"
"0x67C0","POLARIS10_67C0","POLARIS10","POLARIS10"
"0x67C1","POLARIS10_67C1","POLARIS10","POLARIS10"
"0x67C2","POLARIS10_67C2","POLARIS10","POLARIS10"
"0x67C4","POLARIS10_67C4","POLARIS10","POLARIS10"
"0x67C7","POLARIS10_67C7","POLARIS10","POLARIS10"
"0x67DF","POLARIS10_67DF","POLARIS10","POLARIS10"
"0x67C8","POLARIS10_67C8","POLARIS10","POLARIS10"
"0x67C9","POLARIS10_67C9","POLARIS10","POLARIS10"
"0x67CA","POLARIS10_67CA","POLARIS10","POLARIS10"
"0x67CC","POLARIS10_67CC","POLARIS10","POLARIS10"
"0x67CF","POLARIS10_67CF","POLARIS10","POLARIS10"
```

Followed IDs are already blacklisted:

```
"0x6900","TOPAZ_6900","TOPAZ","TOPAZ"
"0x6901","TOPAZ_6901","TOPAZ","TOPAZ"
"0x6902","TOPAZ_6902","TOPAZ","TOPAZ"
"0x6903","TOPAZ_6903","TOPAZ","TOPAZ"
"0x6907","TOPAZ_6907","TOPAZ","TOPAZ"
```

**Comment by philmmanjaro** [comment]
Please test in **unstable** and report back if it is now the wanted result: https://github.com/manjaro/packages-core/commit/fadb7af5d0f869b95a313ca68529ee468e3bf6df

**Comment by SanKro** [comment]
![image](https://cloud.githubusercontent.com/assets/2139158/15978420/27badfb4-2f5e-11e6-9469-65fbb7e14e28.png)
exaclty like it should be. 
Is there a live-CD/Image made from unstable branch? Because the most important part to test would be if it will boot into X (wich is broken right now in 16.06 live media) for GCN1.1,

> even we have enabled experimental support for GCN 1.1 after another user request?

yes. i'm not happy with all this but like you can see in the forums your AMD users really suffers and need to use Netinstaller or the 15.12 install media to be able to install. 

it would still be good to leave the experimental support enabled in the kernel build. so users who are interested in in can just try to switch manually.

**Comment by philmmanjaro** [comment]
You should find some new dev-builds [here](https://sourceforge.net/projects/manjarotest/files/16.08-dev/)

**Comment by SanKro** [comment]
right now only empty folders. but i'll download them if they appear, test and report back. Thanks (:

**Comment by philmmanjaro** [comment]
Yes, I'm currently building them. I had some regressions found regarding **plymouth** so I had to repack them without it to get a working ISO out of it.

**Comment by SanKro** [comment]
thank you for all your work.. thats why we love manjaro

**Comment by SanKro** [comment]
it looks like the changes are not included in the images right now. because
X still cant start
mhwd still tried to sed AMDGPU for kaveri
pacman -Syu tries to update mhwd-ati mhwd-amdgpu

**Comment by philmmanjaro** [comment]
You simply downloaded a **16.06-dev** build. I'm always copy the older image over, rename it and then sync the current ISO over with **rsync**. This saves me upload time. Always wait for the **.sig** file and check if the ISO matches the **shasum**. Please re-download as the fixes are included.

**Comment by SanKro** [comment]
much better now
HDMI/DVI/DP -> on R9 380 works!
HDMI/DVI/DP -> on R7 (GCN1.1) works! (but i have to disable the R9 in UEFI)

as long as the R9 is "active" we can not use the integrated graphics because the Kernel loads AMDGPU Kernel Module and radeon xorg driver dont work with this driver. i dont think its a big deal because who will use the integrated card when there is a better dedicated one.

**Comment by philmmanjaro** [comment]
So we can mark this as solved then?

**Comment by SanKro** [comment]
yes. since it works now.
