### ISSUE TITLE
[linux47] find out why no extramodules will be built

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#51]
Seems we have an issue currently in **x86_64** with extramodules for **4.7.2**. They all fail with following issue:

```
==> Starting build()...
make -C /lib/modules/4.7.2-1-MANJARO/build M=/home/phil/dev/git/manjaro/repositories/extra/linux47-extramodules/acpi_call/src/acpi_call-1.1.0 modules
make[1]: Entering directory '/usr/lib/modules/4.7.2-1-MANJARO/build'
make[2]: *** No rule to make target 'tools/objtool/objtool', needed by '/home/phil/dev/git/manjaro/repositories/extra/linux47-extramodules/acpi_call/src/acpi_call-1.1.0/acpi_call.o'.  Stop.
make[1]: *** [Makefile:1457: _module_/home/phil/dev/git/manjaro/repositories/extra/linux47-extramodules/acpi_call/src/acpi_call-1.1.0] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.7.2-1-MANJARO/build'
make: *** [Makefile:8: default] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by philmmanjaro** [comment]
**i686** [built](https://sourceforge.net/projects/manjarodev/files/users/philm/kernel/linux47-472.tar.xz/download) fine. Also all modules. Maybe somebody else tries to build **linux47** for **x86_64** and give me feedback. Mine is included in that tarball.

**Comment by philmmanjaro** [comment]
Ok, seems somehow **build/tools/objtool/objtool** was not packaged into the **headers** package. Also I found some issues which I'm about to fix ...

**Comment by oberon2007** [comment]
Seems like **4.6.7_rt11** needs a similar treatment...
``make[1]: *** No rule to make target '/var/lib/dkms/broadcom-wl/6.30.223.248/build/src/shared/linux_osl.o', needed by '/var/lib/dkms/broadcom-wl/6.30.223.248/build/wl.o'.  Stop.``
I get this already during kernel install from all dkms-modules. Some for **acpi_call**
Also I see I missed the soc include, too ... :stuck_out_tongue_winking_eye:
