### ISSUE TITLE
revert-intel-asoc.patch no longer needed

### ISSUE THREAD

**Issue by ygyco** [manjaro/packages-core#55]
[revert-intel-asoc.patch](https://github.com/manjaro/packages-core/blob/master/linux48/revert-intel-asoc.patch) is no longer needed as CONFIG_DW_DMAC_CORE=y is set in current manjaro [config](https://github.com/manjaro/packages-core/blob/master/linux48/config.x86_64) (same in arch). Also it should now work even without this [option](https://git.kernel.org/cgit/linux/kernel/git/broonie/sound.git/commit/?h=topic/intel&id=a395bdd6b24b692adbce0df6510ec9f2af57573e) set.

In any case this patch is now redundant and could be dropped.

**Comment by philmmanjaro** [comment]
**CONFIG_DW_DMAC_CORE=y** will be reverted back to the settings we had. Seems it slipped thru by adopting some settings from Arch.
