### ISSUE TITLE
Enable Intel ISH drivers in linux49

### ISSUE THREAD

**Issue by westernmagic** [manjaro/packages-core#57]
Would it be possible to have the new drivers enabled in the coming RC? They have already been mainlined, and are quite stable (on my compiled kernel).
`CONFIG_INTEL_ISH_HID` is the config option.

**Comment by philmmanjaro** [comment]
Will be fixed with: https://github.com/manjaro/packages-core/commit/8d35e9fd26ecb183e81f22335d55293d1e4e2f1f
