### ISSUE TITLE
kernel diferencies

### ISSUE THREAD

**Issue by triceratops1** [manjaro/packages-core#61]
What diferencies has  EXCATCLY  the manjaro and arch kernels?

**Comment by oberon2007** [comment]
Manjaro offers a choice of 8 different base kernels. To each of them a variety of patches is applied. If you want to know in detail, have a look at the PKGBUILDs, like for example [linux44](https://github.com/manjaro/packages-core/blob/master/linux44/PKGBUILD#L77).
