### ISSUE TITLE
pacman-mirrorlist-dev

### ISSUE THREAD

**Issue by fhdk** [manjaro/packages-core#66]
I think the PKGBUILD requires attention.

The package is not on master branch 4.0.0rc but on an old 3.3.0-beta4

**Comment by fhdk** [comment]
thanks :)

It is kind'a weird though that a `pacman -Syu pacman-mirrorlist-dev` gives a 3.3.0.beta6 not a 4.0.0.rc1

**Comment by philmmanjaro** [comment]
@fhdk: which branch do you use? Latest packages are always in **unstable** first.

**Comment by fhdk** [comment]
@philmmanjaro 
I am at unstable
```
## Country       : Denmark
Server = http://www.uex.dk/repos/manjaro/unstable/$repo/$arch

## Country       : Denmark
Server = http://mirrors.dotsrc.org/manjaro/unstable/$repo/$arch

## Country       : Denmark
Server = https://mirrors.dotsrc.org/manjaro/unstable/$repo/$arch
```

**Comment by philmmanjaro** [comment]
We trigger it always manually and upload the packages from our local machines. Latest version just got [uploaded](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170306/010474.html). Mirror **Netzspielplatz** in Germany will pick it up in few minutes.

**Comment by fhdk** [comment]
Could I make you favor me and make build of the rc2 code?

**Comment by oberon2007** [comment]
done. **pacman-mirrorlist-dev-20170313-1-any.pkg.tar.xz** is in unsable now.

**Comment by fhdk** [comment]
On Mon, 2017-03-13 at 05:04 -0700, Bernhard Landauer wrote:
> done. **pacman-mirrorlist-dev-20170313-1-any.pkg.tar.xz** is in
> unsable now.

check - thanks
