### ISSUE TITLE
security updates

### ISSUE THREAD

**Issue by jcmartins** [manjaro/packages-core#67]
Hi, 
I'm up to date but when I run [](https://github.com/steffenfritz/pacaudit) It's found 9 knows security problems in https://security.archlinux.org/

The packages are:
webkitgtk2 is vulnerable.
lib32-libtiff is vulnerable.
libtiff is vulnerable.
jasper is vulnerable.
openjpeg2 is vulnerable.
libusbmuxd is vulnerable.
lib32-libcurl-gnutls is vulnerable.
lib32-curl is vulnerable.
libcurl-gnutls is vulnerable.

Can you fix it?

tks
Joao

**Comment by philmmanjaro** [comment]
Is this still relevant?

**Comment by philmmanjaro** [comment]
reopen if still relevant ...
