### ISSUE TITLE
[kernel] v4.9 series produces an oops on i686

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-core#74]
Currently with **v4.9.31** we have a kernel crash on **i686**.

**Comment by philmmanjaro** [comment]
I've just tested some of the kernels in **i686** bit:

Kernel | Result | GCC
--- | --- | ---
linux411 | failed | gcc7
linux410 | boots | gcc6
linux49 | failed | gcc7
linux48 | TBD | gcc6
linux44 | failed | gcc7
linux41 | boots | gcc6
linux318 | failed | gcc7
linux316 | failed | gcc6
linux312 | TBD | gcc6
linux310 | TBD | gcc6
---

Since I compile them all with a Ryzen 17k I also tested to boot the kernels on **x86_64**

Kernel | Result | GCC
--- | --- | ---
linux412| boots | gcc7
linux411 | boots | gcc7
linux410 | boots | gcc6
linux49 | boots | gcc7
linux48 | boots | gcc6
linux44 | boots | gcc7
linux41 | boots | gcc6
linux318 | failed | gcc7
linux316 | failed | gcc6
linux312 | failed  | gcc6
linux310 | failed | gcc6
---

**Comment by philmmanjaro** [comment]
Seems to be a **toolchain** issue after all. See also [Arch FS#54240](https://bugs.archlinux.org/task/54240).

**Comment by ThanosApostolou** [comment]
There's glibc-2.25-3 on arch's testing. Any chance that you get that in unstable repo in order to see if that fixes the problem?

**Comment by philmmanjaro** [comment]
**glibc-2.25-3** doesn't fix the problem. You can always use `pacman -U <path/to/pkg>` to test it on your own.

**Comment by philmmanjaro** [comment]
I'm happily running the latest **v4.11.5** kernel on **i686** after downgrading **glibc** to the one compiled against **gcc6**. So the whole **toolchain** updated created several issues: **spl** of **zfs** doesn't compile with **gcc7** for example.

**Comment by philmmanjaro** [comment]
Issue is fixed at Arch.
