### ISSUE TITLE
[pacman] Adjust makepkg.conf to Arch new defaults

### ISSUE THREAD

**Issue by VladimirSchowalter20** [manjaro/packages-core#76]
Archlinux changed default CFLAGS in [makepkg.conf](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pacman&id=0cd22d4454e0e1b3ae589b95274f808001465c15)

I think manjaro should do it accordingly.

**Comment by torvic9** [comment]
Makes sense.

**Comment by philmmanjaro** [comment]
Only when we adopt their toolchain and development adjustments to tools.

**Comment by VladimirSchowalter20** [comment]
Not sure what you mean. You already adopted their new gcc and binutils packages. Is there something else?

**Comment by philmmanjaro** [comment]
Well, there is a [pie rebuild](https://www.archlinux.org/todo/pie-rebuild/) going on the needed packages were not yet in core. Seems they are now. I'll check once more.

**Comment by VladimirSchowalter20** [comment]
Done in https://github.com/manjaro/packages-core/commit/33a0bd4937c64069c5f36f42fa88fa4dc25b1e01
