### ISSUE TITLE
Kernel does not recognize BTRFS/XFS filesystem anymore 

### ISSUE THREAD

**Issue by manjaro** [manjaro/packages-core#8]
**linux310**
<pre>[phil@manjaro Arbeitsfläche]$ lsmod | grep xfs
[phil@manjaro Arbeitsfläche]$ sudo modprobe xfs
modprobe: ERROR: could not insert 'xfs': Unknown symbol in module, or unknown parameter (see dmesg)
[phil@manjaro Arbeitsfläche]$ uname -a
Linux manjaro 3.10.68-1-MANJARO #1 SMP Fri Feb 6 17:09:08 UTC 2015 x86_64 GNU/Linux
[phil@manjaro Arbeitsfläche]$ pacman -Ql linux310 | grep xfs
linux310 /usr/lib/modules/3.10.68-1-MANJARO/kernel/fs/xfs/
linux310 /usr/lib/modules/3.10.68-1-MANJARO/kernel/fs/xfs/xfs.ko.gz</pre>

**linux312**
<pre>[phil@manjaro Arbeitsfläche]$ lsmod | grep xfs
[phil@manjaro Arbeitsfläche]$ sudo modprobe xfs
modprobe: ERROR: could not insert 'xfs': Unknown symbol in module, or unknown parameter (see dmesg)
[phil@manjaro Arbeitsfläche]$ uname -a
Linux manjaro 3.12.37-1-MANJARO #1 SMP PREEMPT Sat Jan 31 22:00:15 UTC 2015 x86_64 GNU/Linux
[phil@manjaro Arbeitsfläche]$ pacman -Ql linux312 | grep xfs
linux312 /usr/lib/modules/3.12.37-1-MANJARO/kernel/fs/xfs/
linux312 /usr/lib/modules/3.12.37-1-MANJARO/kernel/fs/xfs/xfs.ko.gz</pre>

**linux314**
<pre>[phil@manjaro Arbeitsfläche]$ lsmod | grep xfs
[phil@manjaro Arbeitsfläche]$ sudo modprobe xfs
modprobe: ERROR: could not insert 'xfs': Unknown symbol in module, or unknown parameter (see dmesg)
[phil@manjaro Arbeitsfläche]$ uname -a
Linux manjaro 3.14.32-1-MANJARO #1 SMP PREEMPT Fri Feb 6 17:50:54 UTC 2015 x86_64 GNU/Linux
[phil@manjaro Arbeitsfläche]$ pacman -Ql linux314 | grep xfs
linux314 /usr/lib/modules/3.14.32-1-MANJARO/kernel/fs/xfs/
linux314 /usr/lib/modules/3.14.32-1-MANJARO/kernel/fs/xfs/xfs.ko.gz</pre>

Filesystems related to **crc32c** are affected too.

**Comment by manjaro** [comment]
**Workaround**
Add at least **crc32c** to **MODULES** line in your **/etc/mkinitcpio.conf** and recompile your initramfs (sudo mkinitcpio -p linux312).

**Comment by manjaro** [comment]
Upstream is now on it:
<pre>Am 09.02.2015 um 20:34 schrieb Kees Cook:
> Hi!
>
> Yeah, this does sound like a regression due to the crypto alias rework. 
> I'm looking through the code now trying to see how crc32c is loaded. 
> Other filesystems do things like this:
> crypto_alloc_shash("crc32c", ...
> but I can't find this in xfs. I'll keep digging...
>
> -Kees</pre>

**Comment by manjaro** [comment]
Seems we found it:

<pre>On 9 February 2015 at 23:05, Greg Kroah-Hartman
<gregkh@linuxfoundation.org> wrote:
> On Mon, Feb 09, 2015 at 01:26:17PM -0800, Kees Cook wrote:
>> But it DOES happen for me on 3.14.31. Hmmm.
>
> Did I mess up the backport somehow?
>

v3.14.31:crypto/crc32c.c is missing the MODULE_ALIAS_CRYPTO("crc32c").
That's probably because crypto/crc32c.c was renamed to
crypto/crc32c_generic.c in commit
06e5a1f29819759392239669beb2cad27059c8ec and therefore fell through
the cracks when backporting commit
5d26a105b5a73e5635eae0629b42fa0a90e07b7b.

So the affected kernels (all that backported the "crypto-" prefix
patches) need this additional patch:

diff --git a/crypto/crc32c.c b/crypto/crc32c.c
index 06f7018c9d95..aae5829eb681 100644
--- a/crypto/crc32c.c
+++ b/crypto/crc32c.c
@@ -167,6 +167,7 @@ static void __exit crc32c_mod_fini(void)
 module_init(crc32c_mod_init);
 module_exit(crc32c_mod_fini);

+MODULE_ALIAS_CRYPTO("crc32c");
 MODULE_AUTHOR("Clay Haapala <chaapala@cisco.com>");
 MODULE_DESCRIPTION("CRC32c (Castagnoli) calculations wrapper for lib/crc32c");
 MODULE_LICENSE("GPL");

Mathias
</pre>

**Comment by philmmanjaro** [comment]
patch is now also queued for next stable releases: [v3.10.69](http://git.kernel.org/cgit/linux/kernel/git/stable/stable-queue.git/commit/?id=ed5c0dc8682ce5da1b0064b16c9c1d811c0e05b7), [v3.14.32](http://git.kernel.org/cgit/linux/kernel/git/stable/stable-queue.git/commit/?id=57260611c720c99b29a1aae7c32b289126343650)

**Comment by korrode** [comment]
Nice one Phil.

**Comment by philmmanjaro** [comment]
As usual ;)

**Comment by manjaro** [comment]
Packages uploaded to [unstable](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150209/002581.html)

**Comment by manjaro** [comment]
Packages uploaded to [testing](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150209/002583.html)
