### ISSUE TITLE
outdated util-linux package

### ISSUE THREAD

**Issue by VladimirSchowalter20** [manjaro/packages-core#80]
Manjaro is supposed to use `util-linux` and `libutil-linux` packages directly from Arch but for some reason it wasn't updated to latest version which Arch did over month ago: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/util-linux&id=253cc6908716858b18a7ef67f079093f9f9c9186

manjaro version: 2.30-2
arch version: 2.30.1-2

I noticed that `lib32-util-linux` package from multilib is updated to latest version already.

Keep in mind that new package is build against new hardened [toolchain](https://github.com/manjaro/packages-core/issues/76). As it contains couple of setuid binaries it's quite important to have this updated.

Of course I'm talking about unstable branch.

**Comment by jonathonf** [comment]
This package provides a metric tonne of core binaries; I'm not sure of the interplay between hardened and non-hardended binaries would be, but I'd easily assume this could cause random issues.

The question is, why this hasn't been synced from upstream?

**Comment by VladimirSchowalter20** [comment]
Manjaro syncs new packages from Arch which are build with new toolchain every few hours so it raises probability that actual issues occur in manjaro.

**Comment by oberon2007** [comment]
We still had some old overlay packages. Afaik they are no longer needed.
I've [removed](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170828/012498.html) them now, so they will be immediately replaced by their Archlinux sync versions.
