### ISSUE TITLE
[filesystem] Consider syncing with latest Archlinux changes

### ISSUE THREAD

**Issue by ghost** [manjaro/packages-core#81]
Archlinux did a lot of changes last week to filesystem package, see https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/filesystem . Probably manjaro should consider if those are needed to sync.

**Comment by philmmanjaro** [comment]
Done via c0ab57b80033c5a97c37c7a05a8572b668304a46, 693b86038cdbc3f0e1a14098d88045179c9cea41, c9e16d20588e13e29924e0faddcb795dbfd18849 and 6ba18748aba71e4b0fc15234c63daa6f106eac63
