### ISSUE TITLE
[grub] Backport ext4 encryption patch

### ISSUE THREAD

**Issue by VladimirSchowalter20** [manjaro/packages-core#82]
Currently grub can't boot when ext4 filesytem has [encryption](https://wiki.archlinux.org/index.php/Ext4#Using_file-based_encryption) flag set. Manjaro can backport patch which exist in grub master tree https://git.savannah.gnu.org/cgit/grub.git/commit/?id=734668238fcc0ef691a080839e04f33854fa133a

**Comment by philmmanjaro** [comment]
We will update **grub** and **grub-quiet** to the lastest git-snapshot.

**Comment by VladimirSchowalter20** [comment]
Thx!
