### ISSUE TITLE
EOL kernels status in manjaro

### ISSUE THREAD

**Issue by ghost** [manjaro/packages-core#83]
For some reason manjaro keeps abandoned linux kernel versions in repos. Currently there are five such kernels:

- [X] linux312 3.12.74 [EOL]
- [ ] linux318 3.18.70 [EOL]
- [X] linux48 4.8.17 [EOL]
- [x] linux410 4.10.17 [EOL]
- [x] linux411 4.11.12 [EOL]
- [x] linux412 4.12.14 [EOL]
- [x] linux413 4.13.16 [EOL]

Some of them weren't updated for months including important security updates. I think manjaro shouldn't keep in it's repos unmaintained software with known security vulnerabilities.

Even if user doesn't want to run newest kernel there are still many older supported versions to choose from. I think there should be deadline, maybe one month after last release and after that kernel package should be deleted from repos.

**Comment by philmmanjaro** [comment]
@oberon2007: was meinst?

**Comment by VladimirSchowalter20** [comment]
What about setting concrete deadline for removal? Let's say 2 moths after last release. This way it would be easier to decide if given kernel is old enough to drop.

**Comment by philmmanjaro** [comment]
It always depends what the community wants. I can do again polls. You will have at least one person who says: Please keep it for another while. From all marked EOL kernels only **linux318** is still get maintained by Greg. Everything else is dead.

**Comment by VladimirSchowalter20** [comment]
If someone has already installed one of those kernels she (he) can keep it infinitely regardless what manjaro do.  It has to clear however that manjaro in no way support those and new users shouldn't find those in manjaro repos.

There are diehards who still run windows xp as it runs best on their machine they claim but vendors like manjaro can set higher standards than that.

Manjaro developers have more knowledge to decide in such matters than average user and have capability to "gentle push" them in right direction. Instead going for full democracy you can be more like meritocracy where vote for yes/no doesn't matters without argumentation which take into account bigger picture than 'works for me' perspective.

**Comment by philmmanjaro** [comment]
[Removed Linux48](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170911/012665.html).

**Comment by philmmanjaro** [comment]
[Removed Linux312](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170911/012666.html).

**Comment by philmmanjaro** [comment]
Started discussion in our [forum](https://forum.manjaro.org/t/cleaning-out-eol-kernels/31007).

**Comment by philmmanjaro** [comment]
[Removed](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170911/012725.html) **linux410** and **linux411**.

**Comment by philmmanjaro** [comment]
I also [removed](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170911/012729.html) **linux310**.

**Comment by Strit** [comment]
[linux318](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/log/?h=v3.18.74) got marked as EOL by Greg yesterday.

**Comment by philmmanjaro** [comment]
@Strit: it got marked month ago, however is still maintained by Greg for some phones. So it isn't really EOL.

**Comment by Huluti** [comment]
Have been resolved and can be closed.
