### ISSUE TITLE
linux 4.13.10 fails to validate two sources

### ISSUE THREAD

**Issue by davidbepo** [manjaro/packages-core#87]
0052-blk-mq-sbitmap-introduce__sbitmap_for_each_set().patch ... HA FALLADO
0055-blk-mq-sched-improve-dispatching-from-sw-queue.patch ... HA FALLADO

**Comment by davidbepo** [comment]
i edited the pkgbuild to skip the checksums and the patches apply correctly
compiling now

**Comment by philmmanjaro** [comment]
@davidbepo: I just redownloaded the patches. No isues on my end.

**Comment by davidbepo** [comment]
the compiled kernel works fine

**Comment by davidbepo** [comment]
it still happens in 4.13.11 :(

**Comment by davidbepo** [comment]
running sha256sum gives me these values
40c2bbd7abd390e0674a797d08f7624051750d38a09d4c42ddba1f8341bb362a  0052-blk-mq-sbitmap-introduce__sbitmap_for_each_set().patch

cfe7d6be0c243bcf6e30f1145991424ad3fa90d43bda214e0df613de007699b6 0055-blk-mq-sched-improve-dispatching-from-sw-queue.patch

**Comment by philmmanjaro** [comment]
Hmm, seems to be the same as with [linux-bfq-mq](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-bfq-mq). Have to check why mine are different.
