### ISSUE TITLE
Add linux kernel patch to fix mmc rpmb partition r/w error

### ISSUE THREAD

**Issue by vincent-t** [manjaro/packages-core#9]
@philmmanjaro Please add this patch: http://permalink.gmane.org/gmane.linux.kernel.mmc/28281 to manjaro kernels. Some netbooks have only mmc memory, without this patch installing manjaro is not possible. 

best regards,

vincent

**Comment by philmmanjaro** [comment]
I'll try to add it on our next kernel cycle. Should I add it to all of our supported kernels?

**Comment by vincent-t** [comment]
Please add it to all kernels. Thank you very much! 

best regards,

vincent

**Comment by philmmanjaro** [comment]
Ok, will add them when new patch-sets are available. Just adding this one patch doesn't make sense for now. Will update the progress here, so you can test it with your hardware.

**Comment by vincent-t** [comment]
Ok, thank you!

**Comment by philmmanjaro** [comment]
Followed kernels already got the patch:
* 3.10.75
* 3.14.39
* 3.19.5

You will find them first in our unstable branch.

**Comment by vincent-t** [comment]
Thank you for adding the patch. Is it allready included in Manjaro 0.8.13-pre1?

best regards,

vincent

**Comment by philmmanjaro** [comment]
We will see. We plan to use linux318 there.

**Comment by philmmanjaro** [comment]
Now also **linux318** has the patch:
* 3.18.12
I'll create soon a new dev-build with it for testing.

**Comment by philmmanjaro** [comment]
Starting with dev-build [0.8.12.104-1 (Apr 24 20:25)](http://sourceforge.net/projects/manjarotest/files/0.8.13/xfce-minimal/0.8.13-dev/) of **Manjaro 0.8.13** we support now mmc by default.

**Comment by vincent-t** [comment]
@philmmanjaro Thank you very much, it works like a charm! Only problem Thus throws errors about the rpmb partition. Nevertheless the installation is successful.

best regards,

vincent

**Comment by philmmanjaro** [comment]
Hi @vincent-t: can you post me the exact error you might get in **thus** cos of it?

**Comment by vincent-t** [comment]
Here you can see the error:
![error](https://cloud.githubusercontent.com/assets/959709/7336863/81d8e61c-ec11-11e4-8796-faff55311f20.jpg)
![log](https://cloud.githubusercontent.com/assets/959709/7336864/81d95dd6-ec11-11e4-9147-307de156b03a.jpg)

**Comment by philmmanjaro** [comment]
Ok, but this error message just pops up but doesn't hurt at your end, or does it prevent you from installing it?

**Comment by vincent-t** [comment]
Installation works fine. The message is just annoying cause it pops up everytime a partition is created / changed.

**Comment by udeved** [comment]
Is this perhaps related to the systemd behaviour 219?
See forum about dev/sdx.device something thread.

**Comment by vincent-t** [comment]
@philmmanjaro Maybe this helps: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1333140

**Comment by philmmanjaro** [comment]
Well, seems this suggested patch is already in **systemd**:
<pre>[phil@manjaro ~]$ cat /usr/lib/udev/rules.d/60-persistent-storage.rules | grep mmc
KERNEL=="fd*|mtd*|nbd*|gnbd*|btibm*|dm-*|md*|zram*|mmcblk[0-9]*rpmb", GOTO="persistent_storage_end"
KERNEL=="mmcblk[0-9]", SUBSYSTEMS=="mmc", ATTRS{name}=="?*", ATTRS{serial}=="?*", ENV{ID_NAME}="$attr{name}", ENV{ID_SERIAL}="$attr{serial}", SYMLINK+="disk/by-id/mmc-$env{ID_NAME}_$env{ID_SERIAL}"
KERNEL=="mmcblk[0-9]p[0-9]", ENV{ID_NAME}=="?*", ENV{ID_SERIAL}=="?*", SYMLINK+="disk/by-id/mmc-$env{ID_NAME}_$env{ID_SERIAL}-part%n"
</pre>
We simply have to ignore mmc then. This has to be done in **Thus**

**Comment by philmmanjaro** [comment]
Please check if **Thus 0.8.12.105** fixes your issue. Simply boot your current disk and use:
<pre>thus -dvu</pre>

**Comment by philmmanjaro** [comment]
Now also **linux316** has the patch:

* 3.16.7.10

**Comment by vincent-t** [comment]
@philmmanjaro How i get Thus 0.8.12.105? I only have Thus 0.8.12.104-1.

**Comment by philmmanjaro** [comment]
@vincent-t: open a terminal inside your live-session and start thus with:
<pre>thus -dvu</pre>
That info was already posted ...

**Comment by philmmanjaro** [comment]
... I forgot to update the info file. Now 0.8.12.106 should be available ...

**Comment by philmmanjaro** [comment]
Else you can install the binary package with:
<pre>sudo pacman -U http://repo.manjaro.org.uk/pool/overlay/thus-dev-0.8.12.106-1-any.pkg.tar.xz</pre>

**Comment by vincent-t** [comment]
@philmmanjaro Sorry that i misunderstood you. I thought I should launch Thus in my installed environment, the old version was still there. Nevermind I got it working. The error is gone but now Thus displays no partition / device. And there are no usefull informations in the log.

**Comment by philmmanjaro** [comment]
@vincent-t : normally it works too. I simply forgot to update the md5 checksum file. Therefor thus didn't update ;) I think I already know why we have this issue with no **/** device. I removed support for mmc now completely. From your screenshot we have **/dev/mmcblk0rpmb** and **/dev/mmcblk0**. Second I don't have to skip. Currently both are skipped ... Let me fix that.

**Comment by philmmanjaro** [comment]
@vincent-t: I think I have it [now](https://github.com/manjaro/thus/commit/744e69c13bd3cb00a6f5ae5522c98c360fc68417):
<pre>sudo pacman -U http://repo.manjaro.org.uk/pool/overlay/thus-dev-0.8.12.106-2-any.pkg.tar.xz</pre>

**Comment by philmmanjaro** [comment]
@vincent-t: we will continue the thus matter [here](https://github.com/manjaro/thus/issues/22) ...

**Comment by philmmanjaro** [comment]
Now also **linux40** and **linux312** has the patch:

* 4.0.1
* 3.12.41

**Comment by philmmanjaro** [comment]
Now also **linux313** has the patch:
* 3.13.11.20
