### ISSUE TITLE
‎ "Lack of "_use_ml1_patches=" and other flags

### ISSUE THREAD

**Issue by michaldybczak** [manjaro/packages-core#92]
I'm writing in name of friends who are knowledgeable in topic and who wrote original patches in AUR versions:

https://gitlab.com/sirlucjan/kernel-patches/raw/master/4.13

There are lacks of codes in given code which renders patches ineffective:

`if [ -n "$_use_ml1_patches" ]; then`

require:

`_use_ml1_patches=`

Without it patches won't overlay on each other, because there is no fulfilled conditions.
Currently `if` calls for none existing flag.

Hopefully my translation of the topic is comprehensible

**Comment by oberon2007** [comment]
Thanks. I don't see what problem you are addressing.
The if clause you mention is nowhere to be found in our patches, so what does this refer to?
Your link broken. The only thing I could find is [this]8https://gitlab.com/sirlucjan/kernel-patches/tree/master/4.13)

**Comment by michaldybczak** [comment]
Sorry for the bad link.
Here is the link for PKGBUILD that lacks of the mentioned flag and thus is broken:
https://github.com/manjaro/packages-core/blob/master/linux413/PKGBUILD

And here the link for source, complete patches:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-bfq-mq

The first 3 flags mentioned in the original PKGBUILD (on the very top) are forgotten in your implementation which brakes the whole patch.

**Comment by oberon2007** [comment]
The patches aren't enabled in the Archlinux PKGBUILD either. To enable them you'd need to set them to anything but empty. We can add the explanatory empty values in the PKGBUILD for clarification. But understand that it won't change anything in the actual package at this moment!

**Comment by oberon2007** [comment]
The question of @philmmanjaro remains if we want to use the patches actually present in the PKGBUILD dir 😉 
There are several `*-blk-mq*` patches, an `ML2*` and a `T000*` patch present without being applied.
So we should either remove or enable them ...

**Comment by michaldybczak** [comment]
Ah, thanks for the explanation :). Closing the topic then.
