### ISSUE TITLE
linux 4.13 fails to download zen temp patch

### ISSUE THREAD

**Issue by davidbepo** [manjaro/packages-core#93]
-> Descargando 0001-zen-temp.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 3 seconds. 3 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 3 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 3 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 500 
==> ERROR: Hubo fallos durante la descarga de https://lkml.org/lkml/diff/2017/9/6/682/1
    Cancelando...

**Comment by philmmanjaro** [comment]
It is a server problem: `The server is taking too long to respond; please wait a minute or 2 and try again.` I've to see if we can grap them from a different server ...

**Comment by davidbepo** [comment]
works now, closing
