### ISSUE TITLE
linux49=4.9.65-1 fails to apply patches

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-core#94]
```
patching file include/linux/printk.h
Hunk #1 succeeded at 40 (offset 3 lines).
patching file drivers/hwmon/k10temp.c
Hunk #1 FAILED at 61.
1 out of 5 hunks FAILED -- saving rejects to file drivers/hwmon/k10temp.c.rej
patch unexpectedly ends in middle of line
```

**Comment by philmmanjaro** [comment]
That is the ZEN patch and not aufs.

**Comment by jonathonf** [comment]
https://github.com/manjaro/packages-core/commit/d6a0c82d78c43d6734314aae3ea865d03418d359 ?

**Comment by philmmanjaro** [comment]
On my end they apply.

**Comment by jonathonf** [comment]
Hmm...

I'm still getting the same thing when trying to compile 4.9.65 for i686...

```
patching file include/linux/printk.h
Hunk #1 succeeded at 40 (offset 3 lines).
patching file drivers/hwmon/k10temp.c
Hunk #1 FAILED at 61.
1 out of 5 hunks FAILED -- saving rejects to file drivers/hwmon/k10temp.c.rej
patch unexpectedly ends in middle of line
```

**Comment by philmmanjaro** [comment]
Please delete your local ZEN patches. If they still don't apply, simply post me the original file and the rejection for debug.

**Comment by jonathonf** [comment]
Oh... I expected patches to be held in the git repo but they're downloaded from upstream. After deleting the cached sources the patches apply cleanly and building starts...
