### ISSUE TITLE
[linux414] kernel 'config' not up-to-date

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-core#99]
When building linux414 I'm prompted to set a number of new options; I it looks like `config` and `config.x86_64` have diverged.

Are options portable? If so, should these files be kept in sync e.g. with a symlink? Or do the settings need to be verified for each $CARCH?

**Comment by torvic9** [comment]
Some options could be newly introduced, maybe? But AFAIK there hasn't been any change from 4.14.1 to 4.14.2., at least on my custom kernel based on this one doesn't have new config options.
What options are new on your side?

**Comment by torvic9** [comment]
Not sure if related but:
```
==> Fix naming schema in BFQ-MQ patch
patching file Makefile
Hunk #1 FAILED at 2.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
```

**Comment by philmmanjaro** [comment]
I never updated the `config` file for **linux414**. We have to see if **archlinux32** has it already.

**Comment by philmmanjaro** [comment]
@jonathonf: you can simply adopt all the default settings when building it with **makepkg** and then adopt [config changes](https://github.com/manjaro/packages-core/commit/9036068e2ffacb587bdf0ad27278a4081ee269b4#diff-297746be9652c5b342614501f018db13) by Archlinux, as I did for 64bit. If needed I can do that for you, as **Archlinux32** doesn't support the **linux** package yet.

**Comment by jonathonf** [comment]
> If needed, I can do that for you

I think that would be helpful so I don't break the config by doing something stupid... plus you know your way around the kernel far better than I do. 😉

**Comment by philmmanjaro** [comment]
@jonathonf: please check and give feedback ...

**Comment by jonathonf** [comment]
It compiled away happily. Now to get the extramodules building...
